// SPDX-FileCopyrightText: 2026 Xquik contributors
//
// SPDX-License-Identifier: Apache-2.0

// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.communities

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CommunityDeleteResponseTest {

    @Test
    fun create() {
        val communityDeleteResponse =
            CommunityDeleteResponse.builder()
                .id("12345")
                .account(
                    CommunityDeleteResponse.Account.builder().id("42").username("example").build()
                )
                .action(CommunityDeleteResponse.Action.LIKE)
                .billing(
                    CommunityDeleteResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(CommunityDeleteResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    CommunityDeleteResponse.NextAction.builder()
                        .type(CommunityDeleteResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    CommunityDeleteResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            CommunityDeleteResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    CommunityDeleteResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(CommunityDeleteResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(CommunityDeleteResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    CommunityDeleteResponse.Target.builder()
                        .id("9876543210")
                        .type(CommunityDeleteResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    CommunityDeleteResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    CommunityDeleteResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(communityDeleteResponse.id()).isEqualTo("12345")
        assertThat(communityDeleteResponse.account())
            .isEqualTo(
                CommunityDeleteResponse.Account.builder().id("42").username("example").build()
            )
        assertThat(communityDeleteResponse.action()).isEqualTo(CommunityDeleteResponse.Action.LIKE)
        assertThat(communityDeleteResponse.billing())
            .isEqualTo(
                CommunityDeleteResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(CommunityDeleteResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(communityDeleteResponse.charged()).isEqualTo(true)
        assertThat(communityDeleteResponse.chargedCredits()).isEqualTo("10")
        assertThat(communityDeleteResponse.nextAction())
            .isEqualTo(
                CommunityDeleteResponse.NextAction.builder()
                    .type(CommunityDeleteResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(communityDeleteResponse.pollAfterMs()).isNull()
        assertThat(communityDeleteResponse.request())
            .isEqualTo(
                CommunityDeleteResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        CommunityDeleteResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(communityDeleteResponse.result())
            .isEqualTo(
                CommunityDeleteResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(CommunityDeleteResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(communityDeleteResponse.retryable()).isEqualTo(false)
        assertThat(communityDeleteResponse.safeToRetry()).isEqualTo(false)
        assertThat(communityDeleteResponse.sendDispatched()).isEqualTo(true)
        assertThat(communityDeleteResponse.status())
            .isEqualTo(CommunityDeleteResponse.Status.SUCCESS)
        assertThat(communityDeleteResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(communityDeleteResponse.success()).isEqualTo(true)
        assertThat(communityDeleteResponse.target())
            .isEqualTo(
                CommunityDeleteResponse.Target.builder()
                    .id("9876543210")
                    .type(CommunityDeleteResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(communityDeleteResponse.targetId()).isEqualTo("9876543210")
        assertThat(communityDeleteResponse.terminal()).isEqualTo(true)
        assertThat(communityDeleteResponse.writeActionId()).isEqualTo("12345")
        assertThat(communityDeleteResponse.communityId()).isEqualTo("3456789012")
        assertThat(communityDeleteResponse.communityName()).isEqualTo("Builders")
        assertThat(communityDeleteResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(communityDeleteResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(communityDeleteResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(communityDeleteResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(communityDeleteResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(communityDeleteResponse.details())
            .isEqualTo(
                CommunityDeleteResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(communityDeleteResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(communityDeleteResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(communityDeleteResponse.idempotent()).isEqualTo(false)
        assertThat(communityDeleteResponse.media())
            .isEqualTo(
                CommunityDeleteResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(communityDeleteResponse.mediaId()).isEqualTo("2345678901")
        assertThat(communityDeleteResponse.mediaUrl())
            .isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(communityDeleteResponse.message())
            .isEqualTo("Invalid input. Check request fields.")
        assertThat(communityDeleteResponse.messageId()).isEqualTo("1234567890")
        assertThat(communityDeleteResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(communityDeleteResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(communityDeleteResponse.resultId()).isEqualTo("9876543210")
        assertThat(communityDeleteResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(communityDeleteResponse.tweetId()).isEqualTo("9876543210")
        assertThat(communityDeleteResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val communityDeleteResponse =
            CommunityDeleteResponse.builder()
                .id("12345")
                .account(
                    CommunityDeleteResponse.Account.builder().id("42").username("example").build()
                )
                .action(CommunityDeleteResponse.Action.LIKE)
                .billing(
                    CommunityDeleteResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(CommunityDeleteResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    CommunityDeleteResponse.NextAction.builder()
                        .type(CommunityDeleteResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    CommunityDeleteResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            CommunityDeleteResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    CommunityDeleteResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(CommunityDeleteResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(CommunityDeleteResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    CommunityDeleteResponse.Target.builder()
                        .id("9876543210")
                        .type(CommunityDeleteResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    CommunityDeleteResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    CommunityDeleteResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedCommunityDeleteResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(communityDeleteResponse),
                jacksonTypeRef<CommunityDeleteResponse>(),
            )

        assertThat(roundtrippedCommunityDeleteResponse).isEqualTo(communityDeleteResponse)
    }
}
