// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.profile

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProfileUpdateAvatarResponseTest {

    @Test
    fun create() {
        val profileUpdateAvatarResponse =
            ProfileUpdateAvatarResponse.builder()
                .id("12345")
                .account(
                    ProfileUpdateAvatarResponse.Account.builder()
                        .id("42")
                        .username("example")
                        .build()
                )
                .action(ProfileUpdateAvatarResponse.Action.LIKE)
                .billing(
                    ProfileUpdateAvatarResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(ProfileUpdateAvatarResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    ProfileUpdateAvatarResponse.NextAction.builder()
                        .type(ProfileUpdateAvatarResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    ProfileUpdateAvatarResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            ProfileUpdateAvatarResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    ProfileUpdateAvatarResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(ProfileUpdateAvatarResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(ProfileUpdateAvatarResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    ProfileUpdateAvatarResponse.Target.builder()
                        .id("9876543210")
                        .type(ProfileUpdateAvatarResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    ProfileUpdateAvatarResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    ProfileUpdateAvatarResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(profileUpdateAvatarResponse.id()).isEqualTo("12345")
        assertThat(profileUpdateAvatarResponse.account())
            .isEqualTo(
                ProfileUpdateAvatarResponse.Account.builder().id("42").username("example").build()
            )
        assertThat(profileUpdateAvatarResponse.action())
            .isEqualTo(ProfileUpdateAvatarResponse.Action.LIKE)
        assertThat(profileUpdateAvatarResponse.billing())
            .isEqualTo(
                ProfileUpdateAvatarResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(ProfileUpdateAvatarResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(profileUpdateAvatarResponse.charged()).isEqualTo(true)
        assertThat(profileUpdateAvatarResponse.chargedCredits()).isEqualTo("10")
        assertThat(profileUpdateAvatarResponse.nextAction())
            .isEqualTo(
                ProfileUpdateAvatarResponse.NextAction.builder()
                    .type(ProfileUpdateAvatarResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(profileUpdateAvatarResponse.pollAfterMs()).isNull()
        assertThat(profileUpdateAvatarResponse.request())
            .isEqualTo(
                ProfileUpdateAvatarResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        ProfileUpdateAvatarResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(profileUpdateAvatarResponse.result())
            .isEqualTo(
                ProfileUpdateAvatarResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(ProfileUpdateAvatarResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(profileUpdateAvatarResponse.retryable()).isEqualTo(false)
        assertThat(profileUpdateAvatarResponse.safeToRetry()).isEqualTo(false)
        assertThat(profileUpdateAvatarResponse.sendDispatched()).isEqualTo(true)
        assertThat(profileUpdateAvatarResponse.status())
            .isEqualTo(ProfileUpdateAvatarResponse.Status.SUCCESS)
        assertThat(profileUpdateAvatarResponse.statusUrl())
            .isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(profileUpdateAvatarResponse.success()).isEqualTo(true)
        assertThat(profileUpdateAvatarResponse.target())
            .isEqualTo(
                ProfileUpdateAvatarResponse.Target.builder()
                    .id("9876543210")
                    .type(ProfileUpdateAvatarResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(profileUpdateAvatarResponse.targetId()).isEqualTo("9876543210")
        assertThat(profileUpdateAvatarResponse.terminal()).isEqualTo(true)
        assertThat(profileUpdateAvatarResponse.writeActionId()).isEqualTo("12345")
        assertThat(profileUpdateAvatarResponse.communityId()).isEqualTo("3456789012")
        assertThat(profileUpdateAvatarResponse.communityName()).isEqualTo("Builders")
        assertThat(profileUpdateAvatarResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(profileUpdateAvatarResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(profileUpdateAvatarResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(profileUpdateAvatarResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(profileUpdateAvatarResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(profileUpdateAvatarResponse.details())
            .isEqualTo(
                ProfileUpdateAvatarResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(profileUpdateAvatarResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(profileUpdateAvatarResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(profileUpdateAvatarResponse.idempotent()).isEqualTo(false)
        assertThat(profileUpdateAvatarResponse.media())
            .isEqualTo(
                ProfileUpdateAvatarResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(profileUpdateAvatarResponse.mediaId()).isEqualTo("2345678901")
        assertThat(profileUpdateAvatarResponse.mediaUrl())
            .isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(profileUpdateAvatarResponse.message())
            .isEqualTo("Invalid input. Check request fields.")
        assertThat(profileUpdateAvatarResponse.messageId()).isEqualTo("1234567890")
        assertThat(profileUpdateAvatarResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(profileUpdateAvatarResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(profileUpdateAvatarResponse.resultId()).isEqualTo("9876543210")
        assertThat(profileUpdateAvatarResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(profileUpdateAvatarResponse.tweetId()).isEqualTo("9876543210")
        assertThat(profileUpdateAvatarResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val profileUpdateAvatarResponse =
            ProfileUpdateAvatarResponse.builder()
                .id("12345")
                .account(
                    ProfileUpdateAvatarResponse.Account.builder()
                        .id("42")
                        .username("example")
                        .build()
                )
                .action(ProfileUpdateAvatarResponse.Action.LIKE)
                .billing(
                    ProfileUpdateAvatarResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(ProfileUpdateAvatarResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    ProfileUpdateAvatarResponse.NextAction.builder()
                        .type(ProfileUpdateAvatarResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    ProfileUpdateAvatarResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            ProfileUpdateAvatarResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    ProfileUpdateAvatarResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(ProfileUpdateAvatarResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(ProfileUpdateAvatarResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    ProfileUpdateAvatarResponse.Target.builder()
                        .id("9876543210")
                        .type(ProfileUpdateAvatarResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    ProfileUpdateAvatarResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    ProfileUpdateAvatarResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedProfileUpdateAvatarResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(profileUpdateAvatarResponse),
                jacksonTypeRef<ProfileUpdateAvatarResponse>(),
            )

        assertThat(roundtrippedProfileUpdateAvatarResponse).isEqualTo(profileUpdateAvatarResponse)
    }
}
