// SPDX-FileCopyrightText: 2026 Xquik contributors
//
// SPDX-License-Identifier: Apache-2.0

// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.profile

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProfileUpdateResponseTest {

    @Test
    fun create() {
        val profileUpdateResponse =
            ProfileUpdateResponse.builder()
                .id("12345")
                .account(
                    ProfileUpdateResponse.Account.builder().id("42").username("example").build()
                )
                .action(ProfileUpdateResponse.Action.LIKE)
                .billing(
                    ProfileUpdateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(ProfileUpdateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    ProfileUpdateResponse.NextAction.builder()
                        .type(ProfileUpdateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    ProfileUpdateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            ProfileUpdateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    ProfileUpdateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(ProfileUpdateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(ProfileUpdateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    ProfileUpdateResponse.Target.builder()
                        .id("9876543210")
                        .type(ProfileUpdateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    ProfileUpdateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    ProfileUpdateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(profileUpdateResponse.id()).isEqualTo("12345")
        assertThat(profileUpdateResponse.account())
            .isEqualTo(ProfileUpdateResponse.Account.builder().id("42").username("example").build())
        assertThat(profileUpdateResponse.action()).isEqualTo(ProfileUpdateResponse.Action.LIKE)
        assertThat(profileUpdateResponse.billing())
            .isEqualTo(
                ProfileUpdateResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(ProfileUpdateResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(profileUpdateResponse.charged()).isEqualTo(true)
        assertThat(profileUpdateResponse.chargedCredits()).isEqualTo("10")
        assertThat(profileUpdateResponse.nextAction())
            .isEqualTo(
                ProfileUpdateResponse.NextAction.builder()
                    .type(ProfileUpdateResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(profileUpdateResponse.pollAfterMs()).isNull()
        assertThat(profileUpdateResponse.request())
            .isEqualTo(
                ProfileUpdateResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        ProfileUpdateResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(profileUpdateResponse.result())
            .isEqualTo(
                ProfileUpdateResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(ProfileUpdateResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(profileUpdateResponse.retryable()).isEqualTo(false)
        assertThat(profileUpdateResponse.safeToRetry()).isEqualTo(false)
        assertThat(profileUpdateResponse.sendDispatched()).isEqualTo(true)
        assertThat(profileUpdateResponse.status()).isEqualTo(ProfileUpdateResponse.Status.SUCCESS)
        assertThat(profileUpdateResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(profileUpdateResponse.success()).isEqualTo(true)
        assertThat(profileUpdateResponse.target())
            .isEqualTo(
                ProfileUpdateResponse.Target.builder()
                    .id("9876543210")
                    .type(ProfileUpdateResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(profileUpdateResponse.targetId()).isEqualTo("9876543210")
        assertThat(profileUpdateResponse.terminal()).isEqualTo(true)
        assertThat(profileUpdateResponse.writeActionId()).isEqualTo("12345")
        assertThat(profileUpdateResponse.communityId()).isEqualTo("3456789012")
        assertThat(profileUpdateResponse.communityName()).isEqualTo("Builders")
        assertThat(profileUpdateResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(profileUpdateResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(profileUpdateResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(profileUpdateResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(profileUpdateResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(profileUpdateResponse.details())
            .isEqualTo(
                ProfileUpdateResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(profileUpdateResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(profileUpdateResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(profileUpdateResponse.idempotent()).isEqualTo(false)
        assertThat(profileUpdateResponse.media())
            .isEqualTo(
                ProfileUpdateResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(profileUpdateResponse.mediaId()).isEqualTo("2345678901")
        assertThat(profileUpdateResponse.mediaUrl())
            .isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(profileUpdateResponse.message())
            .isEqualTo("Invalid input. Check request fields.")
        assertThat(profileUpdateResponse.messageId()).isEqualTo("1234567890")
        assertThat(profileUpdateResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(profileUpdateResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(profileUpdateResponse.resultId()).isEqualTo("9876543210")
        assertThat(profileUpdateResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(profileUpdateResponse.tweetId()).isEqualTo("9876543210")
        assertThat(profileUpdateResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val profileUpdateResponse =
            ProfileUpdateResponse.builder()
                .id("12345")
                .account(
                    ProfileUpdateResponse.Account.builder().id("42").username("example").build()
                )
                .action(ProfileUpdateResponse.Action.LIKE)
                .billing(
                    ProfileUpdateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(ProfileUpdateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    ProfileUpdateResponse.NextAction.builder()
                        .type(ProfileUpdateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    ProfileUpdateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            ProfileUpdateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    ProfileUpdateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(ProfileUpdateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(ProfileUpdateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    ProfileUpdateResponse.Target.builder()
                        .id("9876543210")
                        .type(ProfileUpdateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    ProfileUpdateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    ProfileUpdateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedProfileUpdateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(profileUpdateResponse),
                jacksonTypeRef<ProfileUpdateResponse>(),
            )

        assertThat(roundtrippedProfileUpdateResponse).isEqualTo(profileUpdateResponse)
    }
}
