// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.users.follow

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class FollowCreateResponseTest {

    @Test
    fun create() {
        val followCreateResponse =
            FollowCreateResponse.builder()
                .id("12345")
                .account(
                    FollowCreateResponse.Account.builder().id("42").username("example").build()
                )
                .action(FollowCreateResponse.Action.LIKE)
                .billing(
                    FollowCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(FollowCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    FollowCreateResponse.NextAction.builder()
                        .type(FollowCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    FollowCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            FollowCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    FollowCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(FollowCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(FollowCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    FollowCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(FollowCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    FollowCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    FollowCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(followCreateResponse.id()).isEqualTo("12345")
        assertThat(followCreateResponse.account())
            .isEqualTo(FollowCreateResponse.Account.builder().id("42").username("example").build())
        assertThat(followCreateResponse.action()).isEqualTo(FollowCreateResponse.Action.LIKE)
        assertThat(followCreateResponse.billing())
            .isEqualTo(
                FollowCreateResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(FollowCreateResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(followCreateResponse.charged()).isEqualTo(true)
        assertThat(followCreateResponse.chargedCredits()).isEqualTo("10")
        assertThat(followCreateResponse.nextAction())
            .isEqualTo(
                FollowCreateResponse.NextAction.builder()
                    .type(FollowCreateResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(followCreateResponse.pollAfterMs()).isNull()
        assertThat(followCreateResponse.request())
            .isEqualTo(
                FollowCreateResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        FollowCreateResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(followCreateResponse.result())
            .isEqualTo(
                FollowCreateResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(FollowCreateResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(followCreateResponse.retryable()).isEqualTo(false)
        assertThat(followCreateResponse.safeToRetry()).isEqualTo(false)
        assertThat(followCreateResponse.sendDispatched()).isEqualTo(true)
        assertThat(followCreateResponse.status()).isEqualTo(FollowCreateResponse.Status.SUCCESS)
        assertThat(followCreateResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(followCreateResponse.success()).isEqualTo(true)
        assertThat(followCreateResponse.target())
            .isEqualTo(
                FollowCreateResponse.Target.builder()
                    .id("9876543210")
                    .type(FollowCreateResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(followCreateResponse.targetId()).isEqualTo("9876543210")
        assertThat(followCreateResponse.terminal()).isEqualTo(true)
        assertThat(followCreateResponse.writeActionId()).isEqualTo("12345")
        assertThat(followCreateResponse.communityId()).isEqualTo("3456789012")
        assertThat(followCreateResponse.communityName()).isEqualTo("Builders")
        assertThat(followCreateResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(followCreateResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(followCreateResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(followCreateResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(followCreateResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(followCreateResponse.details())
            .isEqualTo(
                FollowCreateResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(followCreateResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(followCreateResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(followCreateResponse.idempotent()).isEqualTo(false)
        assertThat(followCreateResponse.media())
            .isEqualTo(
                FollowCreateResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(followCreateResponse.mediaId()).isEqualTo("2345678901")
        assertThat(followCreateResponse.mediaUrl()).isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(followCreateResponse.message()).isEqualTo("Invalid input. Check request fields.")
        assertThat(followCreateResponse.messageId()).isEqualTo("1234567890")
        assertThat(followCreateResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(followCreateResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(followCreateResponse.resultId()).isEqualTo("9876543210")
        assertThat(followCreateResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(followCreateResponse.tweetId()).isEqualTo("9876543210")
        assertThat(followCreateResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val followCreateResponse =
            FollowCreateResponse.builder()
                .id("12345")
                .account(
                    FollowCreateResponse.Account.builder().id("42").username("example").build()
                )
                .action(FollowCreateResponse.Action.LIKE)
                .billing(
                    FollowCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(FollowCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    FollowCreateResponse.NextAction.builder()
                        .type(FollowCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    FollowCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            FollowCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    FollowCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(FollowCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(FollowCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    FollowCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(FollowCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    FollowCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    FollowCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedFollowCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(followCreateResponse),
                jacksonTypeRef<FollowCreateResponse>(),
            )

        assertThat(roundtrippedFollowCreateResponse).isEqualTo(followCreateResponse)
    }
}
