// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.dm

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class DmSendResponseTest {

    @Test
    fun create() {
        val dmSendResponse =
            DmSendResponse.builder()
                .id("12345")
                .account(DmSendResponse.Account.builder().id("42").username("example").build())
                .action(DmSendResponse.Action.LIKE)
                .billing(
                    DmSendResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(DmSendResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    DmSendResponse.NextAction.builder()
                        .type(DmSendResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    DmSendResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            DmSendResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    DmSendResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(DmSendResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(DmSendResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    DmSendResponse.Target.builder()
                        .id("9876543210")
                        .type(DmSendResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    DmSendResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    DmSendResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(dmSendResponse.id()).isEqualTo("12345")
        assertThat(dmSendResponse.account())
            .isEqualTo(DmSendResponse.Account.builder().id("42").username("example").build())
        assertThat(dmSendResponse.action()).isEqualTo(DmSendResponse.Action.LIKE)
        assertThat(dmSendResponse.billing())
            .isEqualTo(
                DmSendResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(DmSendResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(dmSendResponse.charged()).isEqualTo(true)
        assertThat(dmSendResponse.chargedCredits()).isEqualTo("10")
        assertThat(dmSendResponse.nextAction())
            .isEqualTo(
                DmSendResponse.NextAction.builder()
                    .type(DmSendResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(dmSendResponse.pollAfterMs()).isNull()
        assertThat(dmSendResponse.request())
            .isEqualTo(
                DmSendResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        DmSendResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(dmSendResponse.result())
            .isEqualTo(
                DmSendResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(DmSendResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(dmSendResponse.retryable()).isEqualTo(false)
        assertThat(dmSendResponse.safeToRetry()).isEqualTo(false)
        assertThat(dmSendResponse.sendDispatched()).isEqualTo(true)
        assertThat(dmSendResponse.status()).isEqualTo(DmSendResponse.Status.SUCCESS)
        assertThat(dmSendResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(dmSendResponse.success()).isEqualTo(true)
        assertThat(dmSendResponse.target())
            .isEqualTo(
                DmSendResponse.Target.builder()
                    .id("9876543210")
                    .type(DmSendResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(dmSendResponse.targetId()).isEqualTo("9876543210")
        assertThat(dmSendResponse.terminal()).isEqualTo(true)
        assertThat(dmSendResponse.writeActionId()).isEqualTo("12345")
        assertThat(dmSendResponse.communityId()).isEqualTo("3456789012")
        assertThat(dmSendResponse.communityName()).isEqualTo("Builders")
        assertThat(dmSendResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(dmSendResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(dmSendResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(dmSendResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(dmSendResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(dmSendResponse.details())
            .isEqualTo(
                DmSendResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(dmSendResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(dmSendResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(dmSendResponse.idempotent()).isEqualTo(false)
        assertThat(dmSendResponse.media())
            .isEqualTo(
                DmSendResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(dmSendResponse.mediaId()).isEqualTo("2345678901")
        assertThat(dmSendResponse.mediaUrl()).isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(dmSendResponse.message()).isEqualTo("Invalid input. Check request fields.")
        assertThat(dmSendResponse.messageId()).isEqualTo("1234567890")
        assertThat(dmSendResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(dmSendResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(dmSendResponse.resultId()).isEqualTo("9876543210")
        assertThat(dmSendResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(dmSendResponse.tweetId()).isEqualTo("9876543210")
        assertThat(dmSendResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val dmSendResponse =
            DmSendResponse.builder()
                .id("12345")
                .account(DmSendResponse.Account.builder().id("42").username("example").build())
                .action(DmSendResponse.Action.LIKE)
                .billing(
                    DmSendResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(DmSendResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    DmSendResponse.NextAction.builder()
                        .type(DmSendResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    DmSendResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            DmSendResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    DmSendResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(DmSendResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(DmSendResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    DmSendResponse.Target.builder()
                        .id("9876543210")
                        .type(DmSendResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    DmSendResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    DmSendResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedDmSendResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(dmSendResponse),
                jacksonTypeRef<DmSendResponse>(),
            )

        assertThat(roundtrippedDmSendResponse).isEqualTo(dmSendResponse)
    }
}
