// SPDX-FileCopyrightText: 2026 Xquik contributors
//
// SPDX-License-Identifier: Apache-2.0

// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.tweets

import com.x_twitter_scraper.api.core.http.QueryParams
import java.time.LocalDate
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TweetSearchParamsTest {

    @Test
    fun create() {
        TweetSearchParams.builder()
            .q("q")
            .advancedQuery("advancedQuery")
            .anyWords("anyWords")
            .blueVerifiedOnly(true)
            .boundingBox("boundingBox")
            .cardName("cardName")
            .cashtags("cashtags")
            .conversationId("conversationId")
            .cursor("cursor")
            .exactPhrase("exactPhrase")
            .excludeSource("excludeSource")
            .excludeWords("excludeWords")
            .fromUser("fromUser")
            .geocode("geocode")
            .hashtags("hashtags")
            .inReplyToTweetId("inReplyToTweetId")
            .language("language")
            .limit(1L)
            .listId("listId")
            .maxFaves(0L)
            .maxId("maxId")
            .maxQuotes(0L)
            .maxReplies(0L)
            .maxRetweets(0L)
            .mediaType(TweetSearchParams.MediaType.IMAGES)
            .mentioning("mentioning")
            .minBookmarks(0L)
            .minFaves(0L)
            .minQuotes(0L)
            .minReplies(0L)
            .minRetweets(0L)
            .minViews(0L)
            .mode(TweetSearchParams.Mode.STANDARD)
            .nativeRetweets(true)
            .near("near")
            .news(true)
            .place("place")
            .placeCountry("placeCountry")
            .pointRadius("pointRadius")
            .queryType(TweetSearchParams.QueryType.LATEST)
            .quotes(TweetSearchParams.Quotes.INCLUDE)
            .quotesOfTweetId("quotesOfTweetId")
            .replies(TweetSearchParams.Replies.INCLUDE)
            .retweets(TweetSearchParams.Retweets.INCLUDE)
            .retweetsOfTweetId("retweetsOfTweetId")
            .safe(true)
            .sinceDate(LocalDate.parse("2019-12-27"))
            .sinceId("sinceId")
            .sinceTime("sinceTime")
            .source("source")
            .toUser("toUser")
            .untilDate(LocalDate.parse("2019-12-27"))
            .untilTime("untilTime")
            .url("url")
            .verifiedOnly(true)
            .within("within")
            .withinTime("withinTime")
            .build()
    }

    @Test
    fun queryParams() {
        val params =
            TweetSearchParams.builder()
                .q("q")
                .advancedQuery("advancedQuery")
                .anyWords("anyWords")
                .blueVerifiedOnly(true)
                .boundingBox("boundingBox")
                .cardName("cardName")
                .cashtags("cashtags")
                .conversationId("conversationId")
                .cursor("cursor")
                .exactPhrase("exactPhrase")
                .excludeSource("excludeSource")
                .excludeWords("excludeWords")
                .fromUser("fromUser")
                .geocode("geocode")
                .hashtags("hashtags")
                .inReplyToTweetId("inReplyToTweetId")
                .language("language")
                .limit(1L)
                .listId("listId")
                .maxFaves(0L)
                .maxId("maxId")
                .maxQuotes(0L)
                .maxReplies(0L)
                .maxRetweets(0L)
                .mediaType(TweetSearchParams.MediaType.IMAGES)
                .mentioning("mentioning")
                .minBookmarks(0L)
                .minFaves(0L)
                .minQuotes(0L)
                .minReplies(0L)
                .minRetweets(0L)
                .minViews(0L)
                .mode(TweetSearchParams.Mode.STANDARD)
                .nativeRetweets(true)
                .near("near")
                .news(true)
                .place("place")
                .placeCountry("placeCountry")
                .pointRadius("pointRadius")
                .queryType(TweetSearchParams.QueryType.LATEST)
                .quotes(TweetSearchParams.Quotes.INCLUDE)
                .quotesOfTweetId("quotesOfTweetId")
                .replies(TweetSearchParams.Replies.INCLUDE)
                .retweets(TweetSearchParams.Retweets.INCLUDE)
                .retweetsOfTweetId("retweetsOfTweetId")
                .safe(true)
                .sinceDate(LocalDate.parse("2019-12-27"))
                .sinceId("sinceId")
                .sinceTime("sinceTime")
                .source("source")
                .toUser("toUser")
                .untilDate(LocalDate.parse("2019-12-27"))
                .untilTime("untilTime")
                .url("url")
                .verifiedOnly(true)
                .within("within")
                .withinTime("withinTime")
                .build()

        val queryParams = params._queryParams()

        assertThat(queryParams)
            .isEqualTo(
                QueryParams.builder()
                    .put("q", "q")
                    .put("advancedQuery", "advancedQuery")
                    .put("anyWords", "anyWords")
                    .put("blueVerifiedOnly", "true")
                    .put("boundingBox", "boundingBox")
                    .put("cardName", "cardName")
                    .put("cashtags", "cashtags")
                    .put("conversationId", "conversationId")
                    .put("cursor", "cursor")
                    .put("exactPhrase", "exactPhrase")
                    .put("excludeSource", "excludeSource")
                    .put("excludeWords", "excludeWords")
                    .put("fromUser", "fromUser")
                    .put("geocode", "geocode")
                    .put("hashtags", "hashtags")
                    .put("inReplyToTweetId", "inReplyToTweetId")
                    .put("language", "language")
                    .put("limit", "1")
                    .put("listId", "listId")
                    .put("maxFaves", "0")
                    .put("maxId", "maxId")
                    .put("maxQuotes", "0")
                    .put("maxReplies", "0")
                    .put("maxRetweets", "0")
                    .put("mediaType", "images")
                    .put("mentioning", "mentioning")
                    .put("minBookmarks", "0")
                    .put("minFaves", "0")
                    .put("minQuotes", "0")
                    .put("minReplies", "0")
                    .put("minRetweets", "0")
                    .put("minViews", "0")
                    .put("mode", "standard")
                    .put("nativeRetweets", "true")
                    .put("near", "near")
                    .put("news", "true")
                    .put("place", "place")
                    .put("placeCountry", "placeCountry")
                    .put("pointRadius", "pointRadius")
                    .put("queryType", "Latest")
                    .put("quotes", "include")
                    .put("quotesOfTweetId", "quotesOfTweetId")
                    .put("replies", "include")
                    .put("retweets", "include")
                    .put("retweetsOfTweetId", "retweetsOfTweetId")
                    .put("safe", "true")
                    .put("sinceDate", "2019-12-27")
                    .put("sinceId", "sinceId")
                    .put("sinceTime", "sinceTime")
                    .put("source", "source")
                    .put("toUser", "toUser")
                    .put("untilDate", "2019-12-27")
                    .put("untilTime", "untilTime")
                    .put("url", "url")
                    .put("verifiedOnly", "true")
                    .put("within", "within")
                    .put("withinTime", "withinTime")
                    .build()
            )
    }

    @Test
    fun queryParamsWithoutOptionalFields() {
        val params = TweetSearchParams.builder().q("q").build()

        val queryParams = params._queryParams()

        assertThat(queryParams).isEqualTo(QueryParams.builder().put("q", "q").build())
    }
}
