// SPDX-FileCopyrightText: 2026 Xquik contributors
//
// SPDX-License-Identifier: Apache-2.0

// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.tweets

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TweetDeleteResponseTest {

    @Test
    fun create() {
        val tweetDeleteResponse =
            TweetDeleteResponse.builder()
                .id("12345")
                .account(TweetDeleteResponse.Account.builder().id("42").username("example").build())
                .action(TweetDeleteResponse.Action.LIKE)
                .billing(
                    TweetDeleteResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(TweetDeleteResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    TweetDeleteResponse.NextAction.builder()
                        .type(TweetDeleteResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    TweetDeleteResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            TweetDeleteResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    TweetDeleteResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(TweetDeleteResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(TweetDeleteResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    TweetDeleteResponse.Target.builder()
                        .id("9876543210")
                        .type(TweetDeleteResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    TweetDeleteResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    TweetDeleteResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(tweetDeleteResponse.id()).isEqualTo("12345")
        assertThat(tweetDeleteResponse.account())
            .isEqualTo(TweetDeleteResponse.Account.builder().id("42").username("example").build())
        assertThat(tweetDeleteResponse.action()).isEqualTo(TweetDeleteResponse.Action.LIKE)
        assertThat(tweetDeleteResponse.billing())
            .isEqualTo(
                TweetDeleteResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(TweetDeleteResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(tweetDeleteResponse.charged()).isEqualTo(true)
        assertThat(tweetDeleteResponse.chargedCredits()).isEqualTo("10")
        assertThat(tweetDeleteResponse.nextAction())
            .isEqualTo(
                TweetDeleteResponse.NextAction.builder()
                    .type(TweetDeleteResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(tweetDeleteResponse.pollAfterMs()).isNull()
        assertThat(tweetDeleteResponse.request())
            .isEqualTo(
                TweetDeleteResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        TweetDeleteResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(tweetDeleteResponse.result())
            .isEqualTo(
                TweetDeleteResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(TweetDeleteResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(tweetDeleteResponse.retryable()).isEqualTo(false)
        assertThat(tweetDeleteResponse.safeToRetry()).isEqualTo(false)
        assertThat(tweetDeleteResponse.sendDispatched()).isEqualTo(true)
        assertThat(tweetDeleteResponse.status()).isEqualTo(TweetDeleteResponse.Status.SUCCESS)
        assertThat(tweetDeleteResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(tweetDeleteResponse.success()).isEqualTo(true)
        assertThat(tweetDeleteResponse.target())
            .isEqualTo(
                TweetDeleteResponse.Target.builder()
                    .id("9876543210")
                    .type(TweetDeleteResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(tweetDeleteResponse.targetId()).isEqualTo("9876543210")
        assertThat(tweetDeleteResponse.terminal()).isEqualTo(true)
        assertThat(tweetDeleteResponse.writeActionId()).isEqualTo("12345")
        assertThat(tweetDeleteResponse.communityId()).isEqualTo("3456789012")
        assertThat(tweetDeleteResponse.communityName()).isEqualTo("Builders")
        assertThat(tweetDeleteResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(tweetDeleteResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(tweetDeleteResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(tweetDeleteResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(tweetDeleteResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(tweetDeleteResponse.details())
            .isEqualTo(
                TweetDeleteResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(tweetDeleteResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(tweetDeleteResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(tweetDeleteResponse.idempotent()).isEqualTo(false)
        assertThat(tweetDeleteResponse.media())
            .isEqualTo(
                TweetDeleteResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(tweetDeleteResponse.mediaId()).isEqualTo("2345678901")
        assertThat(tweetDeleteResponse.mediaUrl()).isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(tweetDeleteResponse.message()).isEqualTo("Invalid input. Check request fields.")
        assertThat(tweetDeleteResponse.messageId()).isEqualTo("1234567890")
        assertThat(tweetDeleteResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(tweetDeleteResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(tweetDeleteResponse.resultId()).isEqualTo("9876543210")
        assertThat(tweetDeleteResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(tweetDeleteResponse.tweetId()).isEqualTo("9876543210")
        assertThat(tweetDeleteResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val tweetDeleteResponse =
            TweetDeleteResponse.builder()
                .id("12345")
                .account(TweetDeleteResponse.Account.builder().id("42").username("example").build())
                .action(TweetDeleteResponse.Action.LIKE)
                .billing(
                    TweetDeleteResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(TweetDeleteResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    TweetDeleteResponse.NextAction.builder()
                        .type(TweetDeleteResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    TweetDeleteResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            TweetDeleteResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    TweetDeleteResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(TweetDeleteResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(TweetDeleteResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    TweetDeleteResponse.Target.builder()
                        .id("9876543210")
                        .type(TweetDeleteResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    TweetDeleteResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    TweetDeleteResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedTweetDeleteResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(tweetDeleteResponse),
                jacksonTypeRef<TweetDeleteResponse>(),
            )

        assertThat(roundtrippedTweetDeleteResponse).isEqualTo(tweetDeleteResponse)
    }
}
