// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.tweets

import com.x_twitter_scraper.api.core.http.QueryParams
import java.time.LocalDate
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TweetSearchParamsTest {

    @Test
    fun create() {
        TweetSearchParams.builder()
            .q("q")
            .advancedQuery("advancedQuery")
            .anyWords("anyWords")
            .boundingBox("boundingBox")
            .cashtags("cashtags")
            .conversationId("conversationId")
            .cursor("cursor")
            .exactPhrase("exactPhrase")
            .excludeWords("excludeWords")
            .fromUser("fromUser")
            .hashtags("hashtags")
            .inReplyToTweetId("inReplyToTweetId")
            .language("language")
            .limit(200L)
            .listId("listId")
            .mediaType(TweetSearchParams.MediaType.IMAGES)
            .mentioning("mentioning")
            .minFaves(0L)
            .minQuotes(0L)
            .minReplies(0L)
            .minRetweets(0L)
            .place("place")
            .placeCountry("placeCountry")
            .pointRadius("pointRadius")
            .queryType(TweetSearchParams.QueryType.LATEST)
            .quotes(TweetSearchParams.Quotes.INCLUDE)
            .quotesOfTweetId("quotesOfTweetId")
            .replies(TweetSearchParams.Replies.INCLUDE)
            .retweets(TweetSearchParams.Retweets.INCLUDE)
            .retweetsOfTweetId("retweetsOfTweetId")
            .sinceDate(LocalDate.parse("2019-12-27"))
            .sinceTime("sinceTime")
            .toUser("toUser")
            .untilDate(LocalDate.parse("2019-12-27"))
            .untilTime("untilTime")
            .url("url")
            .verifiedOnly(true)
            .build()
    }

    @Test
    fun queryParams() {
        val params =
            TweetSearchParams.builder()
                .q("q")
                .advancedQuery("advancedQuery")
                .anyWords("anyWords")
                .boundingBox("boundingBox")
                .cashtags("cashtags")
                .conversationId("conversationId")
                .cursor("cursor")
                .exactPhrase("exactPhrase")
                .excludeWords("excludeWords")
                .fromUser("fromUser")
                .hashtags("hashtags")
                .inReplyToTweetId("inReplyToTweetId")
                .language("language")
                .limit(200L)
                .listId("listId")
                .mediaType(TweetSearchParams.MediaType.IMAGES)
                .mentioning("mentioning")
                .minFaves(0L)
                .minQuotes(0L)
                .minReplies(0L)
                .minRetweets(0L)
                .place("place")
                .placeCountry("placeCountry")
                .pointRadius("pointRadius")
                .queryType(TweetSearchParams.QueryType.LATEST)
                .quotes(TweetSearchParams.Quotes.INCLUDE)
                .quotesOfTweetId("quotesOfTweetId")
                .replies(TweetSearchParams.Replies.INCLUDE)
                .retweets(TweetSearchParams.Retweets.INCLUDE)
                .retweetsOfTweetId("retweetsOfTweetId")
                .sinceDate(LocalDate.parse("2019-12-27"))
                .sinceTime("sinceTime")
                .toUser("toUser")
                .untilDate(LocalDate.parse("2019-12-27"))
                .untilTime("untilTime")
                .url("url")
                .verifiedOnly(true)
                .build()

        val queryParams = params._queryParams()

        assertThat(queryParams)
            .isEqualTo(
                QueryParams.builder()
                    .put("q", "q")
                    .put("advancedQuery", "advancedQuery")
                    .put("anyWords", "anyWords")
                    .put("boundingBox", "boundingBox")
                    .put("cashtags", "cashtags")
                    .put("conversationId", "conversationId")
                    .put("cursor", "cursor")
                    .put("exactPhrase", "exactPhrase")
                    .put("excludeWords", "excludeWords")
                    .put("fromUser", "fromUser")
                    .put("hashtags", "hashtags")
                    .put("inReplyToTweetId", "inReplyToTweetId")
                    .put("language", "language")
                    .put("limit", "200")
                    .put("listId", "listId")
                    .put("mediaType", "images")
                    .put("mentioning", "mentioning")
                    .put("minFaves", "0")
                    .put("minQuotes", "0")
                    .put("minReplies", "0")
                    .put("minRetweets", "0")
                    .put("place", "place")
                    .put("placeCountry", "placeCountry")
                    .put("pointRadius", "pointRadius")
                    .put("queryType", "Latest")
                    .put("quotes", "include")
                    .put("quotesOfTweetId", "quotesOfTweetId")
                    .put("replies", "include")
                    .put("retweets", "include")
                    .put("retweetsOfTweetId", "retweetsOfTweetId")
                    .put("sinceDate", "2019-12-27")
                    .put("sinceTime", "sinceTime")
                    .put("toUser", "toUser")
                    .put("untilDate", "2019-12-27")
                    .put("untilTime", "untilTime")
                    .put("url", "url")
                    .put("verifiedOnly", "true")
                    .build()
            )
    }

    @Test
    fun queryParamsWithoutOptionalFields() {
        val params = TweetSearchParams.builder().q("q").build()

        val queryParams = params._queryParams()

        assertThat(queryParams).isEqualTo(QueryParams.builder().put("q", "q").build())
    }
}
