// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.tweets

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import com.x_twitter_scraper.api.models.UserProfile
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TweetAuthorTest {

    @Test
    fun create() {
        val tweetAuthor =
            TweetAuthor.builder()
                .id("9876543210")
                .name("Elon Musk")
                .username("elonmusk")
                .affiliatesHighlightedLabel(
                    UserProfile.AffiliatesHighlightedLabel.builder()
                        .badgeUrl("badgeUrl")
                        .description("description")
                        .url("url")
                        .urlType("urlType")
                        .userLabelDisplayType("userLabelDisplayType")
                        .userLabelType("userLabelType")
                        .build()
                )
                .automatedBy("example_user")
                .businessAccountAffiliatesCount(0L)
                .communityRole("Member")
                .coverPicture("https://pbs.twimg.com/profile_banners/example.jpg")
                .createdAt("2009-06-02T20:12:29Z")
                .creatorSubscriptionsCount(0L)
                .description("CEO of Tesla, SpaceX, and X")
                .favouritesCount(18000L)
                .followers(150000000L)
                .following(500L)
                .hasCustomTimelines(true)
                .hasGraduatedAccess(true)
                .hasHiddenSubscriptionsOnProfile(true)
                .highlightsInfo(
                    UserProfile.HighlightsInfo.builder()
                        .canHighlightTweets(true)
                        .highlightedTweets("highlightedTweets")
                        .build()
                )
                .identityVerification(
                    UserProfile.IdentityVerification.builder()
                        .description("description")
                        .isIdentityVerified(true)
                        .verifiedSinceMsec("verifiedSinceMsec")
                        .build()
                )
                .isAutomated(false)
                .isBlueVerified(true)
                .isProfileTranslatable(true)
                .isTranslator(false)
                .isVerified(true)
                .location("Austin, TX")
                .mediaCount(1200L)
                .parodyCommentaryFanLabel("parodyCommentaryFanLabel")
                .addPinnedTweetId("1234567890")
                .possiblySensitive(false)
                .profileBio(
                    UserProfile.ProfileBio.builder()
                        .putAdditionalProperty("description", JsonValue.from("bar"))
                        .putAdditionalProperty("entities", JsonValue.from("bar"))
                        .build()
                )
                .profileBannerUrl("https://pbs.twimg.com/profile_banners/example.jpg")
                .profileDescriptionLanguage("profileDescriptionLanguage")
                .profileImageShape("profileImageShape")
                .profileInterstitialType("profileInterstitialType")
                .profilePicture("https://pbs.twimg.com/profile_images/example.jpg")
                .profileSortEnabled(true)
                .profileTranslatorType("profileTranslatorType")
                .protected(false)
                .statusesCount(35000L)
                .superFollowEligible(true)
                .unavailable(false)
                .unavailableReason("suspended")
                .url("https://xquik.com")
                .verified(true)
                .verifiedType("Business")
                .addWithheldInCountry("DE")
                .build()

        assertThat(tweetAuthor.id()).isEqualTo("9876543210")
        assertThat(tweetAuthor.name()).isEqualTo("Elon Musk")
        assertThat(tweetAuthor.username()).isEqualTo("elonmusk")
        assertThat(tweetAuthor.affiliatesHighlightedLabel())
            .isEqualTo(
                UserProfile.AffiliatesHighlightedLabel.builder()
                    .badgeUrl("badgeUrl")
                    .description("description")
                    .url("url")
                    .urlType("urlType")
                    .userLabelDisplayType("userLabelDisplayType")
                    .userLabelType("userLabelType")
                    .build()
            )
        assertThat(tweetAuthor.automatedBy()).isEqualTo("example_user")
        assertThat(tweetAuthor.businessAccountAffiliatesCount()).isEqualTo(0L)
        assertThat(tweetAuthor.communityRole()).isEqualTo("Member")
        assertThat(tweetAuthor.coverPicture())
            .isEqualTo("https://pbs.twimg.com/profile_banners/example.jpg")
        assertThat(tweetAuthor.createdAt()).isEqualTo("2009-06-02T20:12:29Z")
        assertThat(tweetAuthor.creatorSubscriptionsCount()).isEqualTo(0L)
        assertThat(tweetAuthor.description()).isEqualTo("CEO of Tesla, SpaceX, and X")
        assertThat(tweetAuthor.favouritesCount()).isEqualTo(18000L)
        assertThat(tweetAuthor.followers()).isEqualTo(150000000L)
        assertThat(tweetAuthor.following()).isEqualTo(500L)
        assertThat(tweetAuthor.hasCustomTimelines()).isEqualTo(true)
        assertThat(tweetAuthor.hasGraduatedAccess()).isEqualTo(true)
        assertThat(tweetAuthor.hasHiddenSubscriptionsOnProfile()).isEqualTo(true)
        assertThat(tweetAuthor.highlightsInfo())
            .isEqualTo(
                UserProfile.HighlightsInfo.builder()
                    .canHighlightTweets(true)
                    .highlightedTweets("highlightedTweets")
                    .build()
            )
        assertThat(tweetAuthor.identityVerification())
            .isEqualTo(
                UserProfile.IdentityVerification.builder()
                    .description("description")
                    .isIdentityVerified(true)
                    .verifiedSinceMsec("verifiedSinceMsec")
                    .build()
            )
        assertThat(tweetAuthor.isAutomated()).isEqualTo(false)
        assertThat(tweetAuthor.isBlueVerified()).isEqualTo(true)
        assertThat(tweetAuthor.isProfileTranslatable()).isEqualTo(true)
        assertThat(tweetAuthor.isTranslator()).isEqualTo(false)
        assertThat(tweetAuthor.isVerified()).isEqualTo(true)
        assertThat(tweetAuthor.location()).isEqualTo("Austin, TX")
        assertThat(tweetAuthor.mediaCount()).isEqualTo(1200L)
        assertThat(tweetAuthor.parodyCommentaryFanLabel()).isEqualTo("parodyCommentaryFanLabel")
        assertThat(tweetAuthor.pinnedTweetIds()).containsExactly("1234567890")
        assertThat(tweetAuthor.possiblySensitive()).isEqualTo(false)
        assertThat(tweetAuthor.profileBio())
            .isEqualTo(
                UserProfile.ProfileBio.builder()
                    .putAdditionalProperty("description", JsonValue.from("bar"))
                    .putAdditionalProperty("entities", JsonValue.from("bar"))
                    .build()
            )
        assertThat(tweetAuthor.profileBannerUrl())
            .isEqualTo("https://pbs.twimg.com/profile_banners/example.jpg")
        assertThat(tweetAuthor.profileDescriptionLanguage()).isEqualTo("profileDescriptionLanguage")
        assertThat(tweetAuthor.profileImageShape()).isEqualTo("profileImageShape")
        assertThat(tweetAuthor.profileInterstitialType()).isEqualTo("profileInterstitialType")
        assertThat(tweetAuthor.profilePicture())
            .isEqualTo("https://pbs.twimg.com/profile_images/example.jpg")
        assertThat(tweetAuthor.profileSortEnabled()).isEqualTo(true)
        assertThat(tweetAuthor.profileTranslatorType()).isEqualTo("profileTranslatorType")
        assertThat(tweetAuthor.protected()).isEqualTo(false)
        assertThat(tweetAuthor.statusesCount()).isEqualTo(35000L)
        assertThat(tweetAuthor.superFollowEligible()).isEqualTo(true)
        assertThat(tweetAuthor.unavailable()).isEqualTo(false)
        assertThat(tweetAuthor.unavailableReason()).isEqualTo("suspended")
        assertThat(tweetAuthor.url()).isEqualTo("https://xquik.com")
        assertThat(tweetAuthor.verified()).isEqualTo(true)
        assertThat(tweetAuthor.verifiedType()).isEqualTo("Business")
        assertThat(tweetAuthor.withheldInCountries()).containsExactly("DE")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val tweetAuthor =
            TweetAuthor.builder()
                .id("9876543210")
                .name("Elon Musk")
                .username("elonmusk")
                .affiliatesHighlightedLabel(
                    UserProfile.AffiliatesHighlightedLabel.builder()
                        .badgeUrl("badgeUrl")
                        .description("description")
                        .url("url")
                        .urlType("urlType")
                        .userLabelDisplayType("userLabelDisplayType")
                        .userLabelType("userLabelType")
                        .build()
                )
                .automatedBy("example_user")
                .businessAccountAffiliatesCount(0L)
                .communityRole("Member")
                .coverPicture("https://pbs.twimg.com/profile_banners/example.jpg")
                .createdAt("2009-06-02T20:12:29Z")
                .creatorSubscriptionsCount(0L)
                .description("CEO of Tesla, SpaceX, and X")
                .favouritesCount(18000L)
                .followers(150000000L)
                .following(500L)
                .hasCustomTimelines(true)
                .hasGraduatedAccess(true)
                .hasHiddenSubscriptionsOnProfile(true)
                .highlightsInfo(
                    UserProfile.HighlightsInfo.builder()
                        .canHighlightTweets(true)
                        .highlightedTweets("highlightedTweets")
                        .build()
                )
                .identityVerification(
                    UserProfile.IdentityVerification.builder()
                        .description("description")
                        .isIdentityVerified(true)
                        .verifiedSinceMsec("verifiedSinceMsec")
                        .build()
                )
                .isAutomated(false)
                .isBlueVerified(true)
                .isProfileTranslatable(true)
                .isTranslator(false)
                .isVerified(true)
                .location("Austin, TX")
                .mediaCount(1200L)
                .parodyCommentaryFanLabel("parodyCommentaryFanLabel")
                .addPinnedTweetId("1234567890")
                .possiblySensitive(false)
                .profileBio(
                    UserProfile.ProfileBio.builder()
                        .putAdditionalProperty("description", JsonValue.from("bar"))
                        .putAdditionalProperty("entities", JsonValue.from("bar"))
                        .build()
                )
                .profileBannerUrl("https://pbs.twimg.com/profile_banners/example.jpg")
                .profileDescriptionLanguage("profileDescriptionLanguage")
                .profileImageShape("profileImageShape")
                .profileInterstitialType("profileInterstitialType")
                .profilePicture("https://pbs.twimg.com/profile_images/example.jpg")
                .profileSortEnabled(true)
                .profileTranslatorType("profileTranslatorType")
                .protected(false)
                .statusesCount(35000L)
                .superFollowEligible(true)
                .unavailable(false)
                .unavailableReason("suspended")
                .url("https://xquik.com")
                .verified(true)
                .verifiedType("Business")
                .addWithheldInCountry("DE")
                .build()

        val roundtrippedTweetAuthor =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(tweetAuthor),
                jacksonTypeRef<TweetAuthor>(),
            )

        assertThat(roundtrippedTweetAuthor).isEqualTo(tweetAuthor)
    }
}
