// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.tweets

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TweetCreateResponseTest {

    @Test
    fun create() {
        val tweetCreateResponse =
            TweetCreateResponse.builder()
                .id("12345")
                .account(TweetCreateResponse.Account.builder().id("42").username("example").build())
                .action(TweetCreateResponse.Action.LIKE)
                .billing(
                    TweetCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(TweetCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    TweetCreateResponse.NextAction.builder()
                        .type(TweetCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    TweetCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            TweetCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    TweetCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(TweetCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(TweetCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    TweetCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(TweetCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    TweetCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    TweetCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(tweetCreateResponse.id()).isEqualTo("12345")
        assertThat(tweetCreateResponse.account())
            .isEqualTo(TweetCreateResponse.Account.builder().id("42").username("example").build())
        assertThat(tweetCreateResponse.action()).isEqualTo(TweetCreateResponse.Action.LIKE)
        assertThat(tweetCreateResponse.billing())
            .isEqualTo(
                TweetCreateResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(TweetCreateResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(tweetCreateResponse.charged()).isEqualTo(true)
        assertThat(tweetCreateResponse.chargedCredits()).isEqualTo("10")
        assertThat(tweetCreateResponse.nextAction())
            .isEqualTo(
                TweetCreateResponse.NextAction.builder()
                    .type(TweetCreateResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(tweetCreateResponse.pollAfterMs()).isNull()
        assertThat(tweetCreateResponse.request())
            .isEqualTo(
                TweetCreateResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        TweetCreateResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(tweetCreateResponse.result())
            .isEqualTo(
                TweetCreateResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(TweetCreateResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(tweetCreateResponse.retryable()).isEqualTo(false)
        assertThat(tweetCreateResponse.safeToRetry()).isEqualTo(false)
        assertThat(tweetCreateResponse.sendDispatched()).isEqualTo(true)
        assertThat(tweetCreateResponse.status()).isEqualTo(TweetCreateResponse.Status.SUCCESS)
        assertThat(tweetCreateResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(tweetCreateResponse.success()).isEqualTo(true)
        assertThat(tweetCreateResponse.target())
            .isEqualTo(
                TweetCreateResponse.Target.builder()
                    .id("9876543210")
                    .type(TweetCreateResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(tweetCreateResponse.targetId()).isEqualTo("9876543210")
        assertThat(tweetCreateResponse.terminal()).isEqualTo(true)
        assertThat(tweetCreateResponse.writeActionId()).isEqualTo("12345")
        assertThat(tweetCreateResponse.communityId()).isEqualTo("3456789012")
        assertThat(tweetCreateResponse.communityName()).isEqualTo("Builders")
        assertThat(tweetCreateResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(tweetCreateResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(tweetCreateResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(tweetCreateResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(tweetCreateResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(tweetCreateResponse.details())
            .isEqualTo(
                TweetCreateResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(tweetCreateResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(tweetCreateResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(tweetCreateResponse.idempotent()).isEqualTo(false)
        assertThat(tweetCreateResponse.media())
            .isEqualTo(
                TweetCreateResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(tweetCreateResponse.mediaId()).isEqualTo("2345678901")
        assertThat(tweetCreateResponse.mediaUrl()).isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(tweetCreateResponse.message()).isEqualTo("Invalid input. Check request fields.")
        assertThat(tweetCreateResponse.messageId()).isEqualTo("1234567890")
        assertThat(tweetCreateResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(tweetCreateResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(tweetCreateResponse.resultId()).isEqualTo("9876543210")
        assertThat(tweetCreateResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(tweetCreateResponse.tweetId()).isEqualTo("9876543210")
        assertThat(tweetCreateResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val tweetCreateResponse =
            TweetCreateResponse.builder()
                .id("12345")
                .account(TweetCreateResponse.Account.builder().id("42").username("example").build())
                .action(TweetCreateResponse.Action.LIKE)
                .billing(
                    TweetCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(TweetCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    TweetCreateResponse.NextAction.builder()
                        .type(TweetCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    TweetCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            TweetCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    TweetCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(TweetCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(TweetCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    TweetCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(TweetCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    TweetCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    TweetCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedTweetCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(tweetCreateResponse),
                jacksonTypeRef<TweetCreateResponse>(),
            )

        assertThat(roundtrippedTweetCreateResponse).isEqualTo(tweetCreateResponse)
    }
}
