// SPDX-FileCopyrightText: 2026 Xquik contributors
//
// SPDX-License-Identifier: Apache-2.0

// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.tweets.retweet

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RetweetCreateResponseTest {

    @Test
    fun create() {
        val retweetCreateResponse =
            RetweetCreateResponse.builder()
                .id("12345")
                .account(
                    RetweetCreateResponse.Account.builder().id("42").username("example").build()
                )
                .action(RetweetCreateResponse.Action.LIKE)
                .billing(
                    RetweetCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(RetweetCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    RetweetCreateResponse.NextAction.builder()
                        .type(RetweetCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    RetweetCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            RetweetCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    RetweetCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(RetweetCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(RetweetCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    RetweetCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(RetweetCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    RetweetCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    RetweetCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(retweetCreateResponse.id()).isEqualTo("12345")
        assertThat(retweetCreateResponse.account())
            .isEqualTo(RetweetCreateResponse.Account.builder().id("42").username("example").build())
        assertThat(retweetCreateResponse.action()).isEqualTo(RetweetCreateResponse.Action.LIKE)
        assertThat(retweetCreateResponse.billing())
            .isEqualTo(
                RetweetCreateResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(RetweetCreateResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(retweetCreateResponse.charged()).isEqualTo(true)
        assertThat(retweetCreateResponse.chargedCredits()).isEqualTo("10")
        assertThat(retweetCreateResponse.nextAction())
            .isEqualTo(
                RetweetCreateResponse.NextAction.builder()
                    .type(RetweetCreateResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(retweetCreateResponse.pollAfterMs()).isNull()
        assertThat(retweetCreateResponse.request())
            .isEqualTo(
                RetweetCreateResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        RetweetCreateResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(retweetCreateResponse.result())
            .isEqualTo(
                RetweetCreateResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(RetweetCreateResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(retweetCreateResponse.retryable()).isEqualTo(false)
        assertThat(retweetCreateResponse.safeToRetry()).isEqualTo(false)
        assertThat(retweetCreateResponse.sendDispatched()).isEqualTo(true)
        assertThat(retweetCreateResponse.status()).isEqualTo(RetweetCreateResponse.Status.SUCCESS)
        assertThat(retweetCreateResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(retweetCreateResponse.success()).isEqualTo(true)
        assertThat(retweetCreateResponse.target())
            .isEqualTo(
                RetweetCreateResponse.Target.builder()
                    .id("9876543210")
                    .type(RetweetCreateResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(retweetCreateResponse.targetId()).isEqualTo("9876543210")
        assertThat(retweetCreateResponse.terminal()).isEqualTo(true)
        assertThat(retweetCreateResponse.writeActionId()).isEqualTo("12345")
        assertThat(retweetCreateResponse.communityId()).isEqualTo("3456789012")
        assertThat(retweetCreateResponse.communityName()).isEqualTo("Builders")
        assertThat(retweetCreateResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(retweetCreateResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(retweetCreateResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(retweetCreateResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(retweetCreateResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(retweetCreateResponse.details())
            .isEqualTo(
                RetweetCreateResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(retweetCreateResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(retweetCreateResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(retweetCreateResponse.idempotent()).isEqualTo(false)
        assertThat(retweetCreateResponse.media())
            .isEqualTo(
                RetweetCreateResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(retweetCreateResponse.mediaId()).isEqualTo("2345678901")
        assertThat(retweetCreateResponse.mediaUrl())
            .isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(retweetCreateResponse.message())
            .isEqualTo("Invalid input. Check request fields.")
        assertThat(retweetCreateResponse.messageId()).isEqualTo("1234567890")
        assertThat(retweetCreateResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(retweetCreateResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(retweetCreateResponse.resultId()).isEqualTo("9876543210")
        assertThat(retweetCreateResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(retweetCreateResponse.tweetId()).isEqualTo("9876543210")
        assertThat(retweetCreateResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val retweetCreateResponse =
            RetweetCreateResponse.builder()
                .id("12345")
                .account(
                    RetweetCreateResponse.Account.builder().id("42").username("example").build()
                )
                .action(RetweetCreateResponse.Action.LIKE)
                .billing(
                    RetweetCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(RetweetCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    RetweetCreateResponse.NextAction.builder()
                        .type(RetweetCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    RetweetCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            RetweetCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    RetweetCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(RetweetCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(RetweetCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    RetweetCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(RetweetCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    RetweetCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    RetweetCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedRetweetCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(retweetCreateResponse),
                jacksonTypeRef<RetweetCreateResponse>(),
            )

        assertThat(roundtrippedRetweetCreateResponse).isEqualTo(retweetCreateResponse)
    }
}
