// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.tweets.retweet

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RetweetDeleteResponseTest {

    @Test
    fun create() {
        val retweetDeleteResponse =
            RetweetDeleteResponse.builder()
                .id("12345")
                .account(
                    RetweetDeleteResponse.Account.builder().id("42").username("example").build()
                )
                .action(RetweetDeleteResponse.Action.LIKE)
                .billing(
                    RetweetDeleteResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(RetweetDeleteResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    RetweetDeleteResponse.NextAction.builder()
                        .type(RetweetDeleteResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    RetweetDeleteResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            RetweetDeleteResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    RetweetDeleteResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(RetweetDeleteResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(RetweetDeleteResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    RetweetDeleteResponse.Target.builder()
                        .id("9876543210")
                        .type(RetweetDeleteResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    RetweetDeleteResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    RetweetDeleteResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(retweetDeleteResponse.id()).isEqualTo("12345")
        assertThat(retweetDeleteResponse.account())
            .isEqualTo(RetweetDeleteResponse.Account.builder().id("42").username("example").build())
        assertThat(retweetDeleteResponse.action()).isEqualTo(RetweetDeleteResponse.Action.LIKE)
        assertThat(retweetDeleteResponse.billing())
            .isEqualTo(
                RetweetDeleteResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(RetweetDeleteResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(retweetDeleteResponse.charged()).isEqualTo(true)
        assertThat(retweetDeleteResponse.chargedCredits()).isEqualTo("10")
        assertThat(retweetDeleteResponse.nextAction())
            .isEqualTo(
                RetweetDeleteResponse.NextAction.builder()
                    .type(RetweetDeleteResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(retweetDeleteResponse.pollAfterMs()).isNull()
        assertThat(retweetDeleteResponse.request())
            .isEqualTo(
                RetweetDeleteResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        RetweetDeleteResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(retweetDeleteResponse.result())
            .isEqualTo(
                RetweetDeleteResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(RetweetDeleteResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(retweetDeleteResponse.retryable()).isEqualTo(false)
        assertThat(retweetDeleteResponse.safeToRetry()).isEqualTo(false)
        assertThat(retweetDeleteResponse.sendDispatched()).isEqualTo(true)
        assertThat(retweetDeleteResponse.status()).isEqualTo(RetweetDeleteResponse.Status.SUCCESS)
        assertThat(retweetDeleteResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(retweetDeleteResponse.success()).isEqualTo(true)
        assertThat(retweetDeleteResponse.target())
            .isEqualTo(
                RetweetDeleteResponse.Target.builder()
                    .id("9876543210")
                    .type(RetweetDeleteResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(retweetDeleteResponse.targetId()).isEqualTo("9876543210")
        assertThat(retweetDeleteResponse.terminal()).isEqualTo(true)
        assertThat(retweetDeleteResponse.writeActionId()).isEqualTo("12345")
        assertThat(retweetDeleteResponse.communityId()).isEqualTo("3456789012")
        assertThat(retweetDeleteResponse.communityName()).isEqualTo("Builders")
        assertThat(retweetDeleteResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(retweetDeleteResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(retweetDeleteResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(retweetDeleteResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(retweetDeleteResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(retweetDeleteResponse.details())
            .isEqualTo(
                RetweetDeleteResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(retweetDeleteResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(retweetDeleteResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(retweetDeleteResponse.idempotent()).isEqualTo(false)
        assertThat(retweetDeleteResponse.media())
            .isEqualTo(
                RetweetDeleteResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(retweetDeleteResponse.mediaId()).isEqualTo("2345678901")
        assertThat(retweetDeleteResponse.mediaUrl())
            .isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(retweetDeleteResponse.message())
            .isEqualTo("Invalid input. Check request fields.")
        assertThat(retweetDeleteResponse.messageId()).isEqualTo("1234567890")
        assertThat(retweetDeleteResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(retweetDeleteResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(retweetDeleteResponse.resultId()).isEqualTo("9876543210")
        assertThat(retweetDeleteResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(retweetDeleteResponse.tweetId()).isEqualTo("9876543210")
        assertThat(retweetDeleteResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val retweetDeleteResponse =
            RetweetDeleteResponse.builder()
                .id("12345")
                .account(
                    RetweetDeleteResponse.Account.builder().id("42").username("example").build()
                )
                .action(RetweetDeleteResponse.Action.LIKE)
                .billing(
                    RetweetDeleteResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(RetweetDeleteResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    RetweetDeleteResponse.NextAction.builder()
                        .type(RetweetDeleteResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    RetweetDeleteResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            RetweetDeleteResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    RetweetDeleteResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(RetweetDeleteResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(RetweetDeleteResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    RetweetDeleteResponse.Target.builder()
                        .id("9876543210")
                        .type(RetweetDeleteResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    RetweetDeleteResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    RetweetDeleteResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedRetweetDeleteResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(retweetDeleteResponse),
                jacksonTypeRef<RetweetDeleteResponse>(),
            )

        assertThat(roundtrippedRetweetDeleteResponse).isEqualTo(retweetDeleteResponse)
    }
}
