// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EmbeddedTweetTest {

    @Test
    fun create() {
        val embeddedTweet =
            EmbeddedTweet.builder()
                .id("id")
                .bookmarkCount(0L)
                .likeCount(0L)
                .quoteCount(0L)
                .replyCount(0L)
                .retweetCount(0L)
                .text("text")
                .viewCount(0L)
                .author(
                    UserProfile.builder()
                        .id("9876543210")
                        .name("Elon Musk")
                        .username("elonmusk")
                        .automatedBy("example_user")
                        .canDm(false)
                        .communityRole("Member")
                        .coverPicture("https://pbs.twimg.com/profile_banners/example.jpg")
                        .createdAt("2009-06-02T20:12:29Z")
                        .description("CEO of Tesla, SpaceX, and X")
                        .favouritesCount(18000L)
                        .followers(150000000L)
                        .following(500L)
                        .hasCustomTimelines(true)
                        .isAutomated(false)
                        .isBlueVerified(true)
                        .isTranslator(false)
                        .isVerified(true)
                        .location("Austin, TX")
                        .mediaCount(1200L)
                        .addPinnedTweetId("1234567890")
                        .possiblySensitive(false)
                        .profileBio(
                            UserProfile.ProfileBio.builder()
                                .putAdditionalProperty("description", JsonValue.from("bar"))
                                .putAdditionalProperty("entities", JsonValue.from("bar"))
                                .build()
                        )
                        .profileBannerUrl("https://pbs.twimg.com/profile_banners/example.jpg")
                        .profilePicture("https://pbs.twimg.com/profile_images/example.jpg")
                        .protected(false)
                        .statusesCount(35000L)
                        .unavailable(false)
                        .unavailableReason("suspended")
                        .url("https://xquik.com")
                        .verified(true)
                        .verifiedType("Business")
                        .viewerFollowedBy(false)
                        .viewerFollowing(true)
                        .addWithheldInCountry("DE")
                        .build()
                )
                .contentDisclosure(
                    ContentDisclosure.builder()
                        .advertising(
                            ContentDisclosure.Advertising.builder().isPaidPromotion(true).build()
                        )
                        .aiGenerated(
                            ContentDisclosure.AiGenerated.builder()
                                .canEdit(true)
                                .detectionSource("UserDeclared")
                                .hasAiGeneratedMedia(true)
                                .build()
                        )
                        .build()
                )
                .conversationId("conversationId")
                .createdAt("createdAt")
                .addDisplayTextRange(0L)
                .entities(
                    EmbeddedTweet.Entities.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .inReplyToId("inReplyToId")
                .inReplyToUserId("inReplyToUserId")
                .inReplyToUsername("inReplyToUsername")
                .isLimitedReply(true)
                .isNoteTweet(true)
                .isQuoteStatus(true)
                .isReply(true)
                .lang("lang")
                .addMedia(
                    TweetMedia.builder()
                        .mediaUrl("mediaUrl")
                        .type(TweetMedia.Type.PHOTO)
                        .url("url")
                        .addVideoVariant(
                            TweetMedia.VideoVariant.builder()
                                .contentType("contentType")
                                .url("url")
                                .bitrate(0L)
                                .build()
                        )
                        .build()
                )
                .source("source")
                .type("type")
                .url("url")
                .build()

        assertThat(embeddedTweet.id()).isEqualTo("id")
        assertThat(embeddedTweet.bookmarkCount()).isEqualTo(0L)
        assertThat(embeddedTweet.likeCount()).isEqualTo(0L)
        assertThat(embeddedTweet.quoteCount()).isEqualTo(0L)
        assertThat(embeddedTweet.replyCount()).isEqualTo(0L)
        assertThat(embeddedTweet.retweetCount()).isEqualTo(0L)
        assertThat(embeddedTweet.text()).isEqualTo("text")
        assertThat(embeddedTweet.viewCount()).isEqualTo(0L)
        assertThat(embeddedTweet.author())
            .isEqualTo(
                UserProfile.builder()
                    .id("9876543210")
                    .name("Elon Musk")
                    .username("elonmusk")
                    .automatedBy("example_user")
                    .canDm(false)
                    .communityRole("Member")
                    .coverPicture("https://pbs.twimg.com/profile_banners/example.jpg")
                    .createdAt("2009-06-02T20:12:29Z")
                    .description("CEO of Tesla, SpaceX, and X")
                    .favouritesCount(18000L)
                    .followers(150000000L)
                    .following(500L)
                    .hasCustomTimelines(true)
                    .isAutomated(false)
                    .isBlueVerified(true)
                    .isTranslator(false)
                    .isVerified(true)
                    .location("Austin, TX")
                    .mediaCount(1200L)
                    .addPinnedTweetId("1234567890")
                    .possiblySensitive(false)
                    .profileBio(
                        UserProfile.ProfileBio.builder()
                            .putAdditionalProperty("description", JsonValue.from("bar"))
                            .putAdditionalProperty("entities", JsonValue.from("bar"))
                            .build()
                    )
                    .profileBannerUrl("https://pbs.twimg.com/profile_banners/example.jpg")
                    .profilePicture("https://pbs.twimg.com/profile_images/example.jpg")
                    .protected(false)
                    .statusesCount(35000L)
                    .unavailable(false)
                    .unavailableReason("suspended")
                    .url("https://xquik.com")
                    .verified(true)
                    .verifiedType("Business")
                    .viewerFollowedBy(false)
                    .viewerFollowing(true)
                    .addWithheldInCountry("DE")
                    .build()
            )
        assertThat(embeddedTweet.contentDisclosure())
            .isEqualTo(
                ContentDisclosure.builder()
                    .advertising(
                        ContentDisclosure.Advertising.builder().isPaidPromotion(true).build()
                    )
                    .aiGenerated(
                        ContentDisclosure.AiGenerated.builder()
                            .canEdit(true)
                            .detectionSource("UserDeclared")
                            .hasAiGeneratedMedia(true)
                            .build()
                    )
                    .build()
            )
        assertThat(embeddedTweet.conversationId()).isEqualTo("conversationId")
        assertThat(embeddedTweet.createdAt()).isEqualTo("createdAt")
        assertThat(embeddedTweet.displayTextRange()).containsExactly(0L)
        assertThat(embeddedTweet.entities())
            .isEqualTo(
                EmbeddedTweet.Entities.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(embeddedTweet.inReplyToId()).isEqualTo("inReplyToId")
        assertThat(embeddedTweet.inReplyToUserId()).isEqualTo("inReplyToUserId")
        assertThat(embeddedTweet.inReplyToUsername()).isEqualTo("inReplyToUsername")
        assertThat(embeddedTweet.isLimitedReply()).isEqualTo(true)
        assertThat(embeddedTweet.isNoteTweet()).isEqualTo(true)
        assertThat(embeddedTweet.isQuoteStatus()).isEqualTo(true)
        assertThat(embeddedTweet.isReply()).isEqualTo(true)
        assertThat(embeddedTweet.lang()).isEqualTo("lang")
        assertThat(embeddedTweet.media())
            .containsExactly(
                TweetMedia.builder()
                    .mediaUrl("mediaUrl")
                    .type(TweetMedia.Type.PHOTO)
                    .url("url")
                    .addVideoVariant(
                        TweetMedia.VideoVariant.builder()
                            .contentType("contentType")
                            .url("url")
                            .bitrate(0L)
                            .build()
                    )
                    .build()
            )
        assertThat(embeddedTweet.source()).isEqualTo("source")
        assertThat(embeddedTweet.type()).isEqualTo("type")
        assertThat(embeddedTweet.url()).isEqualTo("url")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val embeddedTweet =
            EmbeddedTweet.builder()
                .id("id")
                .bookmarkCount(0L)
                .likeCount(0L)
                .quoteCount(0L)
                .replyCount(0L)
                .retweetCount(0L)
                .text("text")
                .viewCount(0L)
                .author(
                    UserProfile.builder()
                        .id("9876543210")
                        .name("Elon Musk")
                        .username("elonmusk")
                        .automatedBy("example_user")
                        .canDm(false)
                        .communityRole("Member")
                        .coverPicture("https://pbs.twimg.com/profile_banners/example.jpg")
                        .createdAt("2009-06-02T20:12:29Z")
                        .description("CEO of Tesla, SpaceX, and X")
                        .favouritesCount(18000L)
                        .followers(150000000L)
                        .following(500L)
                        .hasCustomTimelines(true)
                        .isAutomated(false)
                        .isBlueVerified(true)
                        .isTranslator(false)
                        .isVerified(true)
                        .location("Austin, TX")
                        .mediaCount(1200L)
                        .addPinnedTweetId("1234567890")
                        .possiblySensitive(false)
                        .profileBio(
                            UserProfile.ProfileBio.builder()
                                .putAdditionalProperty("description", JsonValue.from("bar"))
                                .putAdditionalProperty("entities", JsonValue.from("bar"))
                                .build()
                        )
                        .profileBannerUrl("https://pbs.twimg.com/profile_banners/example.jpg")
                        .profilePicture("https://pbs.twimg.com/profile_images/example.jpg")
                        .protected(false)
                        .statusesCount(35000L)
                        .unavailable(false)
                        .unavailableReason("suspended")
                        .url("https://xquik.com")
                        .verified(true)
                        .verifiedType("Business")
                        .viewerFollowedBy(false)
                        .viewerFollowing(true)
                        .addWithheldInCountry("DE")
                        .build()
                )
                .contentDisclosure(
                    ContentDisclosure.builder()
                        .advertising(
                            ContentDisclosure.Advertising.builder().isPaidPromotion(true).build()
                        )
                        .aiGenerated(
                            ContentDisclosure.AiGenerated.builder()
                                .canEdit(true)
                                .detectionSource("UserDeclared")
                                .hasAiGeneratedMedia(true)
                                .build()
                        )
                        .build()
                )
                .conversationId("conversationId")
                .createdAt("createdAt")
                .addDisplayTextRange(0L)
                .entities(
                    EmbeddedTweet.Entities.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .inReplyToId("inReplyToId")
                .inReplyToUserId("inReplyToUserId")
                .inReplyToUsername("inReplyToUsername")
                .isLimitedReply(true)
                .isNoteTweet(true)
                .isQuoteStatus(true)
                .isReply(true)
                .lang("lang")
                .addMedia(
                    TweetMedia.builder()
                        .mediaUrl("mediaUrl")
                        .type(TweetMedia.Type.PHOTO)
                        .url("url")
                        .addVideoVariant(
                            TweetMedia.VideoVariant.builder()
                                .contentType("contentType")
                                .url("url")
                                .bitrate(0L)
                                .build()
                        )
                        .build()
                )
                .source("source")
                .type("type")
                .url("url")
                .build()

        val roundtrippedEmbeddedTweet =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(embeddedTweet),
                jacksonTypeRef<EmbeddedTweet>(),
            )

        assertThat(roundtrippedEmbeddedTweet).isEqualTo(embeddedTweet)
    }
}
