// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.communities.join

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class JoinCreateResponseTest {

    @Test
    fun create() {
        val joinCreateResponse =
            JoinCreateResponse.builder()
                .id("12345")
                .account(JoinCreateResponse.Account.builder().id("42").username("example").build())
                .action(JoinCreateResponse.Action.LIKE)
                .billing(
                    JoinCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(JoinCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    JoinCreateResponse.NextAction.builder()
                        .type(JoinCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    JoinCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            JoinCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    JoinCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(JoinCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(JoinCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    JoinCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(JoinCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    JoinCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    JoinCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(joinCreateResponse.id()).isEqualTo("12345")
        assertThat(joinCreateResponse.account())
            .isEqualTo(JoinCreateResponse.Account.builder().id("42").username("example").build())
        assertThat(joinCreateResponse.action()).isEqualTo(JoinCreateResponse.Action.LIKE)
        assertThat(joinCreateResponse.billing())
            .isEqualTo(
                JoinCreateResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(JoinCreateResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(joinCreateResponse.charged()).isEqualTo(true)
        assertThat(joinCreateResponse.chargedCredits()).isEqualTo("10")
        assertThat(joinCreateResponse.nextAction())
            .isEqualTo(
                JoinCreateResponse.NextAction.builder()
                    .type(JoinCreateResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(joinCreateResponse.pollAfterMs()).isNull()
        assertThat(joinCreateResponse.request())
            .isEqualTo(
                JoinCreateResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        JoinCreateResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(joinCreateResponse.result())
            .isEqualTo(
                JoinCreateResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(JoinCreateResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(joinCreateResponse.retryable()).isEqualTo(false)
        assertThat(joinCreateResponse.safeToRetry()).isEqualTo(false)
        assertThat(joinCreateResponse.sendDispatched()).isEqualTo(true)
        assertThat(joinCreateResponse.status()).isEqualTo(JoinCreateResponse.Status.SUCCESS)
        assertThat(joinCreateResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(joinCreateResponse.success()).isEqualTo(true)
        assertThat(joinCreateResponse.target())
            .isEqualTo(
                JoinCreateResponse.Target.builder()
                    .id("9876543210")
                    .type(JoinCreateResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(joinCreateResponse.targetId()).isEqualTo("9876543210")
        assertThat(joinCreateResponse.terminal()).isEqualTo(true)
        assertThat(joinCreateResponse.writeActionId()).isEqualTo("12345")
        assertThat(joinCreateResponse.communityId()).isEqualTo("3456789012")
        assertThat(joinCreateResponse.communityName()).isEqualTo("Builders")
        assertThat(joinCreateResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(joinCreateResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(joinCreateResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(joinCreateResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(joinCreateResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(joinCreateResponse.details())
            .isEqualTo(
                JoinCreateResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(joinCreateResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(joinCreateResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(joinCreateResponse.idempotent()).isEqualTo(false)
        assertThat(joinCreateResponse.media())
            .isEqualTo(
                JoinCreateResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(joinCreateResponse.mediaId()).isEqualTo("2345678901")
        assertThat(joinCreateResponse.mediaUrl()).isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(joinCreateResponse.message()).isEqualTo("Invalid input. Check request fields.")
        assertThat(joinCreateResponse.messageId()).isEqualTo("1234567890")
        assertThat(joinCreateResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(joinCreateResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(joinCreateResponse.resultId()).isEqualTo("9876543210")
        assertThat(joinCreateResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(joinCreateResponse.tweetId()).isEqualTo("9876543210")
        assertThat(joinCreateResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val joinCreateResponse =
            JoinCreateResponse.builder()
                .id("12345")
                .account(JoinCreateResponse.Account.builder().id("42").username("example").build())
                .action(JoinCreateResponse.Action.LIKE)
                .billing(
                    JoinCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(JoinCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    JoinCreateResponse.NextAction.builder()
                        .type(JoinCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    JoinCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            JoinCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    JoinCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(JoinCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(JoinCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    JoinCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(JoinCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    JoinCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    JoinCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedJoinCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(joinCreateResponse),
                jacksonTypeRef<JoinCreateResponse>(),
            )

        assertThat(roundtrippedJoinCreateResponse).isEqualTo(joinCreateResponse)
    }
}
