// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.communities.join

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class JoinDeleteAllResponseTest {

    @Test
    fun create() {
        val joinDeleteAllResponse =
            JoinDeleteAllResponse.builder()
                .id("12345")
                .account(
                    JoinDeleteAllResponse.Account.builder().id("42").username("example").build()
                )
                .action(JoinDeleteAllResponse.Action.LIKE)
                .billing(
                    JoinDeleteAllResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(JoinDeleteAllResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    JoinDeleteAllResponse.NextAction.builder()
                        .type(JoinDeleteAllResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    JoinDeleteAllResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            JoinDeleteAllResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    JoinDeleteAllResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(JoinDeleteAllResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(JoinDeleteAllResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    JoinDeleteAllResponse.Target.builder()
                        .id("9876543210")
                        .type(JoinDeleteAllResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    JoinDeleteAllResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    JoinDeleteAllResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(joinDeleteAllResponse.id()).isEqualTo("12345")
        assertThat(joinDeleteAllResponse.account())
            .isEqualTo(JoinDeleteAllResponse.Account.builder().id("42").username("example").build())
        assertThat(joinDeleteAllResponse.action()).isEqualTo(JoinDeleteAllResponse.Action.LIKE)
        assertThat(joinDeleteAllResponse.billing())
            .isEqualTo(
                JoinDeleteAllResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(JoinDeleteAllResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(joinDeleteAllResponse.charged()).isEqualTo(true)
        assertThat(joinDeleteAllResponse.chargedCredits()).isEqualTo("10")
        assertThat(joinDeleteAllResponse.nextAction())
            .isEqualTo(
                JoinDeleteAllResponse.NextAction.builder()
                    .type(JoinDeleteAllResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(joinDeleteAllResponse.pollAfterMs()).isNull()
        assertThat(joinDeleteAllResponse.request())
            .isEqualTo(
                JoinDeleteAllResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        JoinDeleteAllResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(joinDeleteAllResponse.result())
            .isEqualTo(
                JoinDeleteAllResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(JoinDeleteAllResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(joinDeleteAllResponse.retryable()).isEqualTo(false)
        assertThat(joinDeleteAllResponse.safeToRetry()).isEqualTo(false)
        assertThat(joinDeleteAllResponse.sendDispatched()).isEqualTo(true)
        assertThat(joinDeleteAllResponse.status()).isEqualTo(JoinDeleteAllResponse.Status.SUCCESS)
        assertThat(joinDeleteAllResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(joinDeleteAllResponse.success()).isEqualTo(true)
        assertThat(joinDeleteAllResponse.target())
            .isEqualTo(
                JoinDeleteAllResponse.Target.builder()
                    .id("9876543210")
                    .type(JoinDeleteAllResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(joinDeleteAllResponse.targetId()).isEqualTo("9876543210")
        assertThat(joinDeleteAllResponse.terminal()).isEqualTo(true)
        assertThat(joinDeleteAllResponse.writeActionId()).isEqualTo("12345")
        assertThat(joinDeleteAllResponse.communityId()).isEqualTo("3456789012")
        assertThat(joinDeleteAllResponse.communityName()).isEqualTo("Builders")
        assertThat(joinDeleteAllResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(joinDeleteAllResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(joinDeleteAllResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(joinDeleteAllResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(joinDeleteAllResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(joinDeleteAllResponse.details())
            .isEqualTo(
                JoinDeleteAllResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(joinDeleteAllResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(joinDeleteAllResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(joinDeleteAllResponse.idempotent()).isEqualTo(false)
        assertThat(joinDeleteAllResponse.media())
            .isEqualTo(
                JoinDeleteAllResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(joinDeleteAllResponse.mediaId()).isEqualTo("2345678901")
        assertThat(joinDeleteAllResponse.mediaUrl())
            .isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(joinDeleteAllResponse.message())
            .isEqualTo("Invalid input. Check request fields.")
        assertThat(joinDeleteAllResponse.messageId()).isEqualTo("1234567890")
        assertThat(joinDeleteAllResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(joinDeleteAllResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(joinDeleteAllResponse.resultId()).isEqualTo("9876543210")
        assertThat(joinDeleteAllResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(joinDeleteAllResponse.tweetId()).isEqualTo("9876543210")
        assertThat(joinDeleteAllResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val joinDeleteAllResponse =
            JoinDeleteAllResponse.builder()
                .id("12345")
                .account(
                    JoinDeleteAllResponse.Account.builder().id("42").username("example").build()
                )
                .action(JoinDeleteAllResponse.Action.LIKE)
                .billing(
                    JoinDeleteAllResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(JoinDeleteAllResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    JoinDeleteAllResponse.NextAction.builder()
                        .type(JoinDeleteAllResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    JoinDeleteAllResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            JoinDeleteAllResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    JoinDeleteAllResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(JoinDeleteAllResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(JoinDeleteAllResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    JoinDeleteAllResponse.Target.builder()
                        .id("9876543210")
                        .type(JoinDeleteAllResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    JoinDeleteAllResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    JoinDeleteAllResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedJoinDeleteAllResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(joinDeleteAllResponse),
                jacksonTypeRef<JoinDeleteAllResponse>(),
            )

        assertThat(roundtrippedJoinDeleteAllResponse).isEqualTo(joinDeleteAllResponse)
    }
}
