#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

cd "$(dirname "$0")/.."

bash ./bin/check-release-workflow

if command -v ktfmt &> /dev/null; then
    echo "==> Checking ktfmt"
    ./scripts/format --dry-run --set-exit-if-changed
else
    echo "==> Running gradlew lint"
    ./gradlew lint
fi
