// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.extractions

import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ExtractionEstimateCostParamsTest {

    @Test
    fun create() {
        ExtractionEstimateCostParams.builder()
            .toolType(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
            .advancedQuery("min_faves:100")
            .anyWords("ChatGPT AI model")
            .bioContains("bioContains")
            .blueVerifiedOnly(true)
            .boundingBox("-74.1 40.6 -73.9 40.8")
            .cardName("cardName")
            .cashtags("\$TSLA \$NVDA")
            .collectionStrategy(ExtractionEstimateCostParams.CollectionStrategy.AUTO)
            .conversationId("1234567890")
            .dedupeAcrossTargets(true)
            .dedupeMode(ExtractionEstimateCostParams.DedupeMode.NONE)
            .exactPhrase("artificial intelligence")
            .excludeOriginalAuthor(true)
            .excludeSource("excludeSource")
            .excludeWords("spam")
            .fromUser("nasa")
            .geocode("geocode")
            .hashtags("#AI startups")
            .hasLocation(true)
            .hasMediaOnly(true)
            .hasWebsite(true)
            .includeOriginalPost(true)
            .includeSearchTerms(true)
            .includeTargetMetadata(true)
            .inReplyToTweetId("1234567890")
            .language("en")
            .listId("1234567890")
            .locationContains("locationContains")
            .maxDepth(1L)
            .maxFollowers(0L)
            .maxFollowing(0L)
            .maxId("maxId")
            .maxItemsPerTarget(1L)
            .maxLikes(0L)
            .maxPagesPerTarget(1L)
            .maxPosts(0L)
            .maxQuotes(0L)
            .maxReplies(0L)
            .maxRetweets(0L)
            .mediaType(ExtractionEstimateCostParams.MediaType.IMAGES)
            .mentioning("example_user")
            .minAccountAgeDays(0L)
            .minBookmarks(0L)
            .minFaves(10L)
            .minFollowers(0L)
            .minFollowing(0L)
            .minPosts(0L)
            .minQuotes(2L)
            .minReplies(3L)
            .minRetweets(5L)
            .minViews(0L)
            .nativeRetweets(true)
            .near("near")
            .news(true)
            .overlapMode(true)
            .place("96683cc9126741d1")
            .placeCountry("US")
            .pointRadius("-73.99 40.73 25mi")
            .queryType(ExtractionEstimateCostParams.QueryType.LATEST)
            .quotes(ExtractionEstimateCostParams.Quotes.INCLUDE)
            .quotesOfTweetId("1234567890")
            .addRelationTarget(
                ExtractionEstimateCostParams.RelationTarget.builder()
                    .relation(
                        ExtractionEstimateCostParams.RelationTarget.Relation.COMMUNITY_MEMBERS
                    )
                    .value("x")
                    .build()
            )
            .replies(ExtractionEstimateCostParams.Replies.INCLUDE)
            .resultsLimit(1000L)
            .retweets(ExtractionEstimateCostParams.Retweets.EXCLUDE)
            .retweetsOfTweetId("1234567890")
            .safe(true)
            .scope(ExtractionEstimateCostParams.Scope.ALL)
            .addSearchQuery("string")
            .searchQuery("AI trends 2025")
            .sinceDate(LocalDate.parse("2025-01-01"))
            .sinceId("sinceId")
            .sinceTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
            .sort(ExtractionEstimateCostParams.Sort.RELEVANCE)
            .source("source")
            .startCursor("x")
            .targetCommunityId("1500000000000000000")
            .addTargetCommunityId("string")
            .targetListId("1234567890")
            .addTargetListId("string")
            .addTarget("string")
            .targetSpaceId("1vOGwMdBqpwGB")
            .targetTweetId("1234567890")
            .addTargetTweetId("string")
            .targetUsername("elonmusk")
            .addTargetUsername("string")
            .toUser("openai")
            .untilDate(LocalDate.parse("2025-12-31"))
            .untilTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
            .url("example.com")
            .usernameContains("usernameContains")
            .verifiedOnly(false)
            .verifiedType("verifiedType")
            .within("within")
            .withinTime("withinTime")
            .build()
    }

    @Test
    fun body() {
        val params =
            ExtractionEstimateCostParams.builder()
                .toolType(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
                .advancedQuery("min_faves:100")
                .anyWords("ChatGPT AI model")
                .bioContains("bioContains")
                .blueVerifiedOnly(true)
                .boundingBox("-74.1 40.6 -73.9 40.8")
                .cardName("cardName")
                .cashtags("\$TSLA \$NVDA")
                .collectionStrategy(ExtractionEstimateCostParams.CollectionStrategy.AUTO)
                .conversationId("1234567890")
                .dedupeAcrossTargets(true)
                .dedupeMode(ExtractionEstimateCostParams.DedupeMode.NONE)
                .exactPhrase("artificial intelligence")
                .excludeOriginalAuthor(true)
                .excludeSource("excludeSource")
                .excludeWords("spam")
                .fromUser("nasa")
                .geocode("geocode")
                .hashtags("#AI startups")
                .hasLocation(true)
                .hasMediaOnly(true)
                .hasWebsite(true)
                .includeOriginalPost(true)
                .includeSearchTerms(true)
                .includeTargetMetadata(true)
                .inReplyToTweetId("1234567890")
                .language("en")
                .listId("1234567890")
                .locationContains("locationContains")
                .maxDepth(1L)
                .maxFollowers(0L)
                .maxFollowing(0L)
                .maxId("maxId")
                .maxItemsPerTarget(1L)
                .maxLikes(0L)
                .maxPagesPerTarget(1L)
                .maxPosts(0L)
                .maxQuotes(0L)
                .maxReplies(0L)
                .maxRetweets(0L)
                .mediaType(ExtractionEstimateCostParams.MediaType.IMAGES)
                .mentioning("example_user")
                .minAccountAgeDays(0L)
                .minBookmarks(0L)
                .minFaves(10L)
                .minFollowers(0L)
                .minFollowing(0L)
                .minPosts(0L)
                .minQuotes(2L)
                .minReplies(3L)
                .minRetweets(5L)
                .minViews(0L)
                .nativeRetweets(true)
                .near("near")
                .news(true)
                .overlapMode(true)
                .place("96683cc9126741d1")
                .placeCountry("US")
                .pointRadius("-73.99 40.73 25mi")
                .queryType(ExtractionEstimateCostParams.QueryType.LATEST)
                .quotes(ExtractionEstimateCostParams.Quotes.INCLUDE)
                .quotesOfTweetId("1234567890")
                .addRelationTarget(
                    ExtractionEstimateCostParams.RelationTarget.builder()
                        .relation(
                            ExtractionEstimateCostParams.RelationTarget.Relation.COMMUNITY_MEMBERS
                        )
                        .value("x")
                        .build()
                )
                .replies(ExtractionEstimateCostParams.Replies.INCLUDE)
                .resultsLimit(1000L)
                .retweets(ExtractionEstimateCostParams.Retweets.EXCLUDE)
                .retweetsOfTweetId("1234567890")
                .safe(true)
                .scope(ExtractionEstimateCostParams.Scope.ALL)
                .addSearchQuery("string")
                .searchQuery("AI trends 2025")
                .sinceDate(LocalDate.parse("2025-01-01"))
                .sinceId("sinceId")
                .sinceTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .sort(ExtractionEstimateCostParams.Sort.RELEVANCE)
                .source("source")
                .startCursor("x")
                .targetCommunityId("1500000000000000000")
                .addTargetCommunityId("string")
                .targetListId("1234567890")
                .addTargetListId("string")
                .addTarget("string")
                .targetSpaceId("1vOGwMdBqpwGB")
                .targetTweetId("1234567890")
                .addTargetTweetId("string")
                .targetUsername("elonmusk")
                .addTargetUsername("string")
                .toUser("openai")
                .untilDate(LocalDate.parse("2025-12-31"))
                .untilTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .url("example.com")
                .usernameContains("usernameContains")
                .verifiedOnly(false)
                .verifiedType("verifiedType")
                .within("within")
                .withinTime("withinTime")
                .build()

        val body = params._body()

        assertThat(body.toolType())
            .isEqualTo(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
        assertThat(body.advancedQuery()).isEqualTo("min_faves:100")
        assertThat(body.anyWords()).isEqualTo("ChatGPT AI model")
        assertThat(body.bioContains()).isEqualTo("bioContains")
        assertThat(body.blueVerifiedOnly()).isEqualTo(true)
        assertThat(body.boundingBox()).isEqualTo("-74.1 40.6 -73.9 40.8")
        assertThat(body.cardName()).isEqualTo("cardName")
        assertThat(body.cashtags()).isEqualTo("\$TSLA \$NVDA")
        assertThat(body.collectionStrategy())
            .isEqualTo(ExtractionEstimateCostParams.CollectionStrategy.AUTO)
        assertThat(body.conversationId()).isEqualTo("1234567890")
        assertThat(body.dedupeAcrossTargets()).isEqualTo(true)
        assertThat(body.dedupeMode()).isEqualTo(ExtractionEstimateCostParams.DedupeMode.NONE)
        assertThat(body.exactPhrase()).isEqualTo("artificial intelligence")
        assertThat(body.excludeOriginalAuthor()).isEqualTo(true)
        assertThat(body.excludeSource()).isEqualTo("excludeSource")
        assertThat(body.excludeWords()).isEqualTo("spam")
        assertThat(body.fromUser()).isEqualTo("nasa")
        assertThat(body.geocode()).isEqualTo("geocode")
        assertThat(body.hashtags()).isEqualTo("#AI startups")
        assertThat(body.hasLocation()).isEqualTo(true)
        assertThat(body.hasMediaOnly()).isEqualTo(true)
        assertThat(body.hasWebsite()).isEqualTo(true)
        assertThat(body.includeOriginalPost()).isEqualTo(true)
        assertThat(body.includeSearchTerms()).isEqualTo(true)
        assertThat(body.includeTargetMetadata()).isEqualTo(true)
        assertThat(body.inReplyToTweetId()).isEqualTo("1234567890")
        assertThat(body.language()).isEqualTo("en")
        assertThat(body.listId()).isEqualTo("1234567890")
        assertThat(body.locationContains()).isEqualTo("locationContains")
        assertThat(body.maxDepth()).isEqualTo(1L)
        assertThat(body.maxFollowers()).isEqualTo(0L)
        assertThat(body.maxFollowing()).isEqualTo(0L)
        assertThat(body.maxId()).isEqualTo("maxId")
        assertThat(body.maxItemsPerTarget()).isEqualTo(1L)
        assertThat(body.maxLikes()).isEqualTo(0L)
        assertThat(body.maxPagesPerTarget()).isEqualTo(1L)
        assertThat(body.maxPosts()).isEqualTo(0L)
        assertThat(body.maxQuotes()).isEqualTo(0L)
        assertThat(body.maxReplies()).isEqualTo(0L)
        assertThat(body.maxRetweets()).isEqualTo(0L)
        assertThat(body.mediaType()).isEqualTo(ExtractionEstimateCostParams.MediaType.IMAGES)
        assertThat(body.mentioning()).isEqualTo("example_user")
        assertThat(body.minAccountAgeDays()).isEqualTo(0L)
        assertThat(body.minBookmarks()).isEqualTo(0L)
        assertThat(body.minFaves()).isEqualTo(10L)
        assertThat(body.minFollowers()).isEqualTo(0L)
        assertThat(body.minFollowing()).isEqualTo(0L)
        assertThat(body.minPosts()).isEqualTo(0L)
        assertThat(body.minQuotes()).isEqualTo(2L)
        assertThat(body.minReplies()).isEqualTo(3L)
        assertThat(body.minRetweets()).isEqualTo(5L)
        assertThat(body.minViews()).isEqualTo(0L)
        assertThat(body.nativeRetweets()).isEqualTo(true)
        assertThat(body.near()).isEqualTo("near")
        assertThat(body.news()).isEqualTo(true)
        assertThat(body.overlapMode()).isEqualTo(true)
        assertThat(body.place()).isEqualTo("96683cc9126741d1")
        assertThat(body.placeCountry()).isEqualTo("US")
        assertThat(body.pointRadius()).isEqualTo("-73.99 40.73 25mi")
        assertThat(body.queryType()).isEqualTo(ExtractionEstimateCostParams.QueryType.LATEST)
        assertThat(body.quotes()).isEqualTo(ExtractionEstimateCostParams.Quotes.INCLUDE)
        assertThat(body.quotesOfTweetId()).isEqualTo("1234567890")
        assertThat(body.relationTargets())
            .containsExactly(
                ExtractionEstimateCostParams.RelationTarget.builder()
                    .relation(
                        ExtractionEstimateCostParams.RelationTarget.Relation.COMMUNITY_MEMBERS
                    )
                    .value("x")
                    .build()
            )
        assertThat(body.replies()).isEqualTo(ExtractionEstimateCostParams.Replies.INCLUDE)
        assertThat(body.resultsLimit()).isEqualTo(1000L)
        assertThat(body.retweets()).isEqualTo(ExtractionEstimateCostParams.Retweets.EXCLUDE)
        assertThat(body.retweetsOfTweetId()).isEqualTo("1234567890")
        assertThat(body.safe()).isEqualTo(true)
        assertThat(body.scope()).isEqualTo(ExtractionEstimateCostParams.Scope.ALL)
        assertThat(body.searchQueries()).containsExactly("string")
        assertThat(body.searchQuery()).isEqualTo("AI trends 2025")
        assertThat(body.sinceDate()).isEqualTo(LocalDate.parse("2025-01-01"))
        assertThat(body.sinceId()).isEqualTo("sinceId")
        assertThat(body.sinceTime())
            .isEqualTo(
                ExtractionEstimateCostParams.SinceTime.ofOffsetDate(
                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                )
            )
        assertThat(body.sort()).isEqualTo(ExtractionEstimateCostParams.Sort.RELEVANCE)
        assertThat(body.source()).isEqualTo("source")
        assertThat(body.startCursor()).isEqualTo("x")
        assertThat(body.targetCommunityId()).isEqualTo("1500000000000000000")
        assertThat(body.targetCommunityIds()).containsExactly("string")
        assertThat(body.targetListId()).isEqualTo("1234567890")
        assertThat(body.targetListIds()).containsExactly("string")
        assertThat(body.targets())
            .containsExactly(ExtractionEstimateCostParams.Target.ofString("string"))
        assertThat(body.targetSpaceId()).isEqualTo("1vOGwMdBqpwGB")
        assertThat(body.targetTweetId()).isEqualTo("1234567890")
        assertThat(body.targetTweetIds()).containsExactly("string")
        assertThat(body.targetUsername()).isEqualTo("elonmusk")
        assertThat(body.targetUsernames()).containsExactly("string")
        assertThat(body.toUser()).isEqualTo("openai")
        assertThat(body.untilDate()).isEqualTo(LocalDate.parse("2025-12-31"))
        assertThat(body.untilTime())
            .isEqualTo(
                ExtractionEstimateCostParams.UntilTime.ofOffsetDate(
                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                )
            )
        assertThat(body.url()).isEqualTo("example.com")
        assertThat(body.usernameContains()).isEqualTo("usernameContains")
        assertThat(body.verifiedOnly()).isEqualTo(false)
        assertThat(body.verifiedType()).isEqualTo("verifiedType")
        assertThat(body.within()).isEqualTo("within")
        assertThat(body.withinTime()).isEqualTo("withinTime")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            ExtractionEstimateCostParams.builder()
                .toolType(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
                .build()

        val body = params._body()

        assertThat(body.toolType())
            .isEqualTo(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
    }
}
