// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.tweets.like

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class LikeCreateResponseTest {

    @Test
    fun create() {
        val likeCreateResponse =
            LikeCreateResponse.builder()
                .id("12345")
                .account(LikeCreateResponse.Account.builder().id("42").username("example").build())
                .action(LikeCreateResponse.Action.LIKE)
                .billing(
                    LikeCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(LikeCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    LikeCreateResponse.NextAction.builder()
                        .type(LikeCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    LikeCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            LikeCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    LikeCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(LikeCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(LikeCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    LikeCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(LikeCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    LikeCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    LikeCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(likeCreateResponse.id()).isEqualTo("12345")
        assertThat(likeCreateResponse.account())
            .isEqualTo(LikeCreateResponse.Account.builder().id("42").username("example").build())
        assertThat(likeCreateResponse.action()).isEqualTo(LikeCreateResponse.Action.LIKE)
        assertThat(likeCreateResponse.billing())
            .isEqualTo(
                LikeCreateResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(LikeCreateResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(likeCreateResponse.charged()).isEqualTo(true)
        assertThat(likeCreateResponse.chargedCredits()).isEqualTo("10")
        assertThat(likeCreateResponse.nextAction())
            .isEqualTo(
                LikeCreateResponse.NextAction.builder()
                    .type(LikeCreateResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(likeCreateResponse.pollAfterMs()).isNull()
        assertThat(likeCreateResponse.request())
            .isEqualTo(
                LikeCreateResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        LikeCreateResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(likeCreateResponse.result())
            .isEqualTo(
                LikeCreateResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(LikeCreateResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(likeCreateResponse.retryable()).isEqualTo(false)
        assertThat(likeCreateResponse.safeToRetry()).isEqualTo(false)
        assertThat(likeCreateResponse.sendDispatched()).isEqualTo(true)
        assertThat(likeCreateResponse.status()).isEqualTo(LikeCreateResponse.Status.SUCCESS)
        assertThat(likeCreateResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(likeCreateResponse.success()).isEqualTo(true)
        assertThat(likeCreateResponse.target())
            .isEqualTo(
                LikeCreateResponse.Target.builder()
                    .id("9876543210")
                    .type(LikeCreateResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(likeCreateResponse.targetId()).isEqualTo("9876543210")
        assertThat(likeCreateResponse.terminal()).isEqualTo(true)
        assertThat(likeCreateResponse.writeActionId()).isEqualTo("12345")
        assertThat(likeCreateResponse.communityId()).isEqualTo("3456789012")
        assertThat(likeCreateResponse.communityName()).isEqualTo("Builders")
        assertThat(likeCreateResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(likeCreateResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(likeCreateResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(likeCreateResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(likeCreateResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(likeCreateResponse.details())
            .isEqualTo(
                LikeCreateResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(likeCreateResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(likeCreateResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(likeCreateResponse.idempotent()).isEqualTo(false)
        assertThat(likeCreateResponse.media())
            .isEqualTo(
                LikeCreateResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(likeCreateResponse.mediaId()).isEqualTo("2345678901")
        assertThat(likeCreateResponse.mediaUrl()).isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(likeCreateResponse.message()).isEqualTo("Invalid input. Check request fields.")
        assertThat(likeCreateResponse.messageId()).isEqualTo("1234567890")
        assertThat(likeCreateResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(likeCreateResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(likeCreateResponse.resultId()).isEqualTo("9876543210")
        assertThat(likeCreateResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(likeCreateResponse.tweetId()).isEqualTo("9876543210")
        assertThat(likeCreateResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val likeCreateResponse =
            LikeCreateResponse.builder()
                .id("12345")
                .account(LikeCreateResponse.Account.builder().id("42").username("example").build())
                .action(LikeCreateResponse.Action.LIKE)
                .billing(
                    LikeCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(LikeCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    LikeCreateResponse.NextAction.builder()
                        .type(LikeCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    LikeCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            LikeCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    LikeCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(LikeCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(LikeCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    LikeCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(LikeCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    LikeCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    LikeCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedLikeCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(likeCreateResponse),
                jacksonTypeRef<LikeCreateResponse>(),
            )

        assertThat(roundtrippedLikeCreateResponse).isEqualTo(likeCreateResponse)
    }
}
