// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.tweets.like

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class LikeDeleteResponseTest {

    @Test
    fun create() {
        val likeDeleteResponse =
            LikeDeleteResponse.builder()
                .id("12345")
                .account(LikeDeleteResponse.Account.builder().id("42").username("example").build())
                .action(LikeDeleteResponse.Action.LIKE)
                .billing(
                    LikeDeleteResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(LikeDeleteResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    LikeDeleteResponse.NextAction.builder()
                        .type(LikeDeleteResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    LikeDeleteResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            LikeDeleteResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    LikeDeleteResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(LikeDeleteResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(LikeDeleteResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    LikeDeleteResponse.Target.builder()
                        .id("9876543210")
                        .type(LikeDeleteResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    LikeDeleteResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    LikeDeleteResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(likeDeleteResponse.id()).isEqualTo("12345")
        assertThat(likeDeleteResponse.account())
            .isEqualTo(LikeDeleteResponse.Account.builder().id("42").username("example").build())
        assertThat(likeDeleteResponse.action()).isEqualTo(LikeDeleteResponse.Action.LIKE)
        assertThat(likeDeleteResponse.billing())
            .isEqualTo(
                LikeDeleteResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(LikeDeleteResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(likeDeleteResponse.charged()).isEqualTo(true)
        assertThat(likeDeleteResponse.chargedCredits()).isEqualTo("10")
        assertThat(likeDeleteResponse.nextAction())
            .isEqualTo(
                LikeDeleteResponse.NextAction.builder()
                    .type(LikeDeleteResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(likeDeleteResponse.pollAfterMs()).isNull()
        assertThat(likeDeleteResponse.request())
            .isEqualTo(
                LikeDeleteResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        LikeDeleteResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(likeDeleteResponse.result())
            .isEqualTo(
                LikeDeleteResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(LikeDeleteResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(likeDeleteResponse.retryable()).isEqualTo(false)
        assertThat(likeDeleteResponse.safeToRetry()).isEqualTo(false)
        assertThat(likeDeleteResponse.sendDispatched()).isEqualTo(true)
        assertThat(likeDeleteResponse.status()).isEqualTo(LikeDeleteResponse.Status.SUCCESS)
        assertThat(likeDeleteResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(likeDeleteResponse.success()).isEqualTo(true)
        assertThat(likeDeleteResponse.target())
            .isEqualTo(
                LikeDeleteResponse.Target.builder()
                    .id("9876543210")
                    .type(LikeDeleteResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(likeDeleteResponse.targetId()).isEqualTo("9876543210")
        assertThat(likeDeleteResponse.terminal()).isEqualTo(true)
        assertThat(likeDeleteResponse.writeActionId()).isEqualTo("12345")
        assertThat(likeDeleteResponse.communityId()).isEqualTo("3456789012")
        assertThat(likeDeleteResponse.communityName()).isEqualTo("Builders")
        assertThat(likeDeleteResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(likeDeleteResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(likeDeleteResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(likeDeleteResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(likeDeleteResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(likeDeleteResponse.details())
            .isEqualTo(
                LikeDeleteResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(likeDeleteResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(likeDeleteResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(likeDeleteResponse.idempotent()).isEqualTo(false)
        assertThat(likeDeleteResponse.media())
            .isEqualTo(
                LikeDeleteResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(likeDeleteResponse.mediaId()).isEqualTo("2345678901")
        assertThat(likeDeleteResponse.mediaUrl()).isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(likeDeleteResponse.message()).isEqualTo("Invalid input. Check request fields.")
        assertThat(likeDeleteResponse.messageId()).isEqualTo("1234567890")
        assertThat(likeDeleteResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(likeDeleteResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(likeDeleteResponse.resultId()).isEqualTo("9876543210")
        assertThat(likeDeleteResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(likeDeleteResponse.tweetId()).isEqualTo("9876543210")
        assertThat(likeDeleteResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val likeDeleteResponse =
            LikeDeleteResponse.builder()
                .id("12345")
                .account(LikeDeleteResponse.Account.builder().id("42").username("example").build())
                .action(LikeDeleteResponse.Action.LIKE)
                .billing(
                    LikeDeleteResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(LikeDeleteResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    LikeDeleteResponse.NextAction.builder()
                        .type(LikeDeleteResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    LikeDeleteResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            LikeDeleteResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    LikeDeleteResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(LikeDeleteResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(LikeDeleteResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    LikeDeleteResponse.Target.builder()
                        .id("9876543210")
                        .type(LikeDeleteResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    LikeDeleteResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    LikeDeleteResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedLikeDeleteResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(likeDeleteResponse),
                jacksonTypeRef<LikeDeleteResponse>(),
            )

        assertThat(roundtrippedLikeDeleteResponse).isEqualTo(likeDeleteResponse)
    }
}
