// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.users

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class UserRemoveFollowerResponseTest {

    @Test
    fun create() {
        val userRemoveFollowerResponse =
            UserRemoveFollowerResponse.builder()
                .id("12345")
                .account(
                    UserRemoveFollowerResponse.Account.builder()
                        .id("42")
                        .username("example")
                        .build()
                )
                .action(UserRemoveFollowerResponse.Action.LIKE)
                .billing(
                    UserRemoveFollowerResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(UserRemoveFollowerResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    UserRemoveFollowerResponse.NextAction.builder()
                        .type(UserRemoveFollowerResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    UserRemoveFollowerResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            UserRemoveFollowerResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    UserRemoveFollowerResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(UserRemoveFollowerResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(UserRemoveFollowerResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    UserRemoveFollowerResponse.Target.builder()
                        .id("9876543210")
                        .type(UserRemoveFollowerResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    UserRemoveFollowerResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    UserRemoveFollowerResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(userRemoveFollowerResponse.id()).isEqualTo("12345")
        assertThat(userRemoveFollowerResponse.account())
            .isEqualTo(
                UserRemoveFollowerResponse.Account.builder().id("42").username("example").build()
            )
        assertThat(userRemoveFollowerResponse.action())
            .isEqualTo(UserRemoveFollowerResponse.Action.LIKE)
        assertThat(userRemoveFollowerResponse.billing())
            .isEqualTo(
                UserRemoveFollowerResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(UserRemoveFollowerResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(userRemoveFollowerResponse.charged()).isEqualTo(true)
        assertThat(userRemoveFollowerResponse.chargedCredits()).isEqualTo("10")
        assertThat(userRemoveFollowerResponse.nextAction())
            .isEqualTo(
                UserRemoveFollowerResponse.NextAction.builder()
                    .type(UserRemoveFollowerResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(userRemoveFollowerResponse.pollAfterMs()).isNull()
        assertThat(userRemoveFollowerResponse.request())
            .isEqualTo(
                UserRemoveFollowerResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        UserRemoveFollowerResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(userRemoveFollowerResponse.result())
            .isEqualTo(
                UserRemoveFollowerResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(UserRemoveFollowerResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(userRemoveFollowerResponse.retryable()).isEqualTo(false)
        assertThat(userRemoveFollowerResponse.safeToRetry()).isEqualTo(false)
        assertThat(userRemoveFollowerResponse.sendDispatched()).isEqualTo(true)
        assertThat(userRemoveFollowerResponse.status())
            .isEqualTo(UserRemoveFollowerResponse.Status.SUCCESS)
        assertThat(userRemoveFollowerResponse.statusUrl())
            .isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(userRemoveFollowerResponse.success()).isEqualTo(true)
        assertThat(userRemoveFollowerResponse.target())
            .isEqualTo(
                UserRemoveFollowerResponse.Target.builder()
                    .id("9876543210")
                    .type(UserRemoveFollowerResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(userRemoveFollowerResponse.targetId()).isEqualTo("9876543210")
        assertThat(userRemoveFollowerResponse.terminal()).isEqualTo(true)
        assertThat(userRemoveFollowerResponse.writeActionId()).isEqualTo("12345")
        assertThat(userRemoveFollowerResponse.communityId()).isEqualTo("3456789012")
        assertThat(userRemoveFollowerResponse.communityName()).isEqualTo("Builders")
        assertThat(userRemoveFollowerResponse.completedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(userRemoveFollowerResponse.confirmationAttempts()).isEqualTo(1L)
        assertThat(userRemoveFollowerResponse.confirmationCheckedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(userRemoveFollowerResponse.confirmedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(userRemoveFollowerResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(userRemoveFollowerResponse.details())
            .isEqualTo(
                UserRemoveFollowerResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userRemoveFollowerResponse.error()).isEqualTo("x_write_ambiguous")
        assertThat(userRemoveFollowerResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(userRemoveFollowerResponse.idempotent()).isEqualTo(false)
        assertThat(userRemoveFollowerResponse.media())
            .isEqualTo(
                UserRemoveFollowerResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userRemoveFollowerResponse.mediaId()).isEqualTo("2345678901")
        assertThat(userRemoveFollowerResponse.mediaUrl())
            .isEqualTo("https://media.xquik.com/example.jpg")
        assertThat(userRemoveFollowerResponse.message())
            .isEqualTo("Invalid input. Check request fields.")
        assertThat(userRemoveFollowerResponse.messageId()).isEqualTo("1234567890")
        assertThat(userRemoveFollowerResponse.requestHash())
            .isEqualTo("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(userRemoveFollowerResponse.requestId()).isEqualTo("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(userRemoveFollowerResponse.resultId()).isEqualTo("9876543210")
        assertThat(userRemoveFollowerResponse.sendDispatchedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(userRemoveFollowerResponse.tweetId()).isEqualTo("9876543210")
        assertThat(userRemoveFollowerResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val userRemoveFollowerResponse =
            UserRemoveFollowerResponse.builder()
                .id("12345")
                .account(
                    UserRemoveFollowerResponse.Account.builder()
                        .id("42")
                        .username("example")
                        .build()
                )
                .action(UserRemoveFollowerResponse.Action.LIKE)
                .billing(
                    UserRemoveFollowerResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(UserRemoveFollowerResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    UserRemoveFollowerResponse.NextAction.builder()
                        .type(UserRemoveFollowerResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    UserRemoveFollowerResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            UserRemoveFollowerResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    UserRemoveFollowerResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(UserRemoveFollowerResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(UserRemoveFollowerResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    UserRemoveFollowerResponse.Target.builder()
                        .id("9876543210")
                        .type(UserRemoveFollowerResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    UserRemoveFollowerResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    UserRemoveFollowerResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedUserRemoveFollowerResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(userRemoveFollowerResponse),
                jacksonTypeRef<UserRemoveFollowerResponse>(),
            )

        assertThat(roundtrippedUserRemoveFollowerResponse).isEqualTo(userRemoveFollowerResponse)
    }
}
